### ISSUE TITLE
Get JupyterHub admin access for Data8X hub

### ISSUE THREAD

**Issue by sauravmittal** [berkeley-dsep-infra/datahub#1000]
Here's my info:

Saurav Mittal
edx-id: saurav_mittal
My users for the three courses:
630b33bc007fc68a4912b90d85443224
e3a956bffbae67d42744ef08be58a48e
030777d951ba972876eaab81c3bceb21

**Comment by felder** [comment]
@sideye Can you please confirm that this request for admin access is valid?

**Comment by fqzbdkh** [comment]
Grace Li
EdX ID: GraceLi07
8.1x hub ID: 461ee9f934be0a3079ba12ecc066939b
8.2x hub ID: 780e0c299d28f5ab0d505ec8dfffd898
8.3x hub ID: ccd399c54550718cafa19b4a2e230bfc

**Comment by sideye** [comment]
Both are valid; Grace and Saurav are new members on the 8X support staff. There should be another request from Ervin (@ebaccay) as well.

**Comment by felder** [comment]
@sideye Thanks!

**Comment by felder** [comment]
Grace and Saurav have been added.  @ebaccay please add your ids to this ticket and I'll them too.

**Comment by felder** [comment]
@ebaccay added.

**Comment by manikui** [comment]
Hi I'm requesting admin access for the Data 8X hub.

edX ID: manikui
8.1x = 8.2x = 8.3x: d921b4caaa1fe484094618ead010445d

**Comment by kvah** [comment]
> Hi I'm requesting admin access for the Data 8X hub.
> 
> edX ID: manikui
> 8.1x = 8.2x = 8.3x: d921b4caaa1fe484094618ead010445d

confirmed

**Comment by sideye** [comment]
confirmed

**Comment by sideye** [comment]
> Hi I'm requesting admin access for the Data 8X hub.
> 
> edX ID: manikui
> 8.1x = 8.2x = 8.3x: d921b4caaa1fe484094618ead010445d

confirmed

**Comment by felder** [comment]
@manikui @kvah @sideye In the future if additional work needs to be done, please reopen or create a new issue.  Don't just replied to a close one.  Open issues are how we keep track of work.  Thanks.

**Comment by felder** [comment]
Deployed to prod.
