### ISSUE TITLE
Request python package "umap" for "Physics 188/288" + resource request

### ISSUE THREAD

**Issue by ybh0822** [berkeley-dsep-infra/datahub#1001]
**Which package do you want installed?**
umap (https://umap-learn.readthedocs.io/en/latest/index.html)

**Which class will use this package?**
Physics 188/288 (Bayesian Data Analysis and Machine Learning for Physical Sciences, https://classes.berkeley.edu/content/2019-fall-physics-188-001-lec-001)

**Which semester will this package be used for?**
Fall 2019

**Any additional information we should know about?**
As for the resources, would it be possible to have 2GB RAM?

Thanks,
Byeonghee

**Comment by felder** [comment]
@ybh0822 scikit-learn 0.21.3 installed
