### ISSUE TITLE
Request python package "hdbscan" for "Physics 188/288"

### ISSUE THREAD

**Issue by ybh0822** [berkeley-dsep-infra/datahub#1015]
**Which package do you want installed?**
hdbscan (https://hdbscan.readthedocs.io/en/latest/)

**Which class will use this package?**
Physics 188/288 (Bayesian Data Analysis and Machine Learning for Physical Sciences, https://classes.berkeley.edu/content/2019-fall-physics-188-001-lec-001)

**Which semester will this package be used for?**
Fall 2019

Sorry for submitting another issue :( We are still making changes to the course assignment.
Thank you for your help and consideration.

**Comment by felder** [comment]
Merged to prod.
