### ISSUE TITLE
Sponsored guests accounts merge on same email prefix

### ISSUE THREAD

**Issue by nolanpokpongkiat** [berkeley-dsep-infra/datahub#1016]
I'm testing out a sponsored guest account for a cross-enrolled student with a non-berkeley email for the hub. I tested this out by sponsoring my own gmail (nolanpokpongkiat@gmail.com) on bcourses and then spawning a hub from that, but logging in with nolanpokpongkiat@gmail.com brought to my original account on nolanpokpongkiat@berkeley.edu. I understand this is due to my having the same email prefix under both domains, but would this be a possible edge case to address?

I don't know what the probability of two students having the same email prefix from berkeley and a sponsored outside domain is, but just wanted to put this on the radar. Other than that, hub seems to work fine off a sponsored account!

**Comment by yuvipanda** [comment]
<3 thanks for reporting this, @nolanpokpongkiat!

Fixed by #1020. For non-berkeley.edu accounts, we use the full email as the username for disambiguation.
