### ISSUE TITLE
Request python package simpleaudio for EPS 109 

### ISSUE THREAD

**Issue by ericvd-ucb** [berkeley-dsep-infra/datahub#1030]
**Which package do you want installed?**
simpleaudio
**Which class will use this package?**
EPS 109 
Burkhard Militzer
https://classes.berkeley.edu/content/2019-fall-eps-109-001-lec-001

**Which semester will this package be used for?**
Fall 2019

**Any additional information we should know about?**

**Comment by felder** [comment]
When attempting to install simpleaudio, I got a build failure that references alsa:

```
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DDEBUG=0 -I/srv/app/venv/include -I/usr/include/python3.6m -c c_src/simpleaudio_alsa.c -o build/temp.linux-x86_64-3.6/c_src/simpleaudio_alsa.o
    c_src/simpleaudio_alsa.c:8:10: fatal error: alsa/asoundlib.h: No such file or directory
     #include <alsa/asoundlib.h>
              ^~~~~~~~~~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/srv/app/venv/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-49rcv8pg/simpleaudio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-7m507qjx-record/install-record.txt --single-version-externally-managed --compile --install-headers /srv/app/venv/include/site/python3.6/simpleaudio" failed with error code 1 in /tmp/pip-build-49rcv8pg/simpleaudio/
```

I suspected that because of the references to alsa that it might not be possible to use simpleaudio in the hub environment.  @yuvipanda confirmed this suspicion.  He also indicated that this might work:

https://stackoverflow.com/questions/16241944/playing-a-sound-in-a-ipython-notebook/30741861#30741861

**Comment by ericvd-ucb** [comment]
OK thanks guys  - sorry for wasting your time!
