### ISSUE TITLE
Possibly ephemeral I/O issue

### ISSUE THREAD

**Issue by ryanlovett** [berkeley-dsep-infra/datahub#1034]
A data102 user reported (Mon, Sep 16, 2019 at 11:39 PM
) in the data102 piazza that they received a disk I/O exception when duplicating a notebook file. I was able duplicate their file as them this morning.

![unnamed](https://user-images.githubusercontent.com/10248125/65061164-36a4be00-d92e-11e9-9170-138310bf63a7.png)
![unnamed (1)](https://user-images.githubusercontent.com/10248125/65061172-3a384500-d92e-11e9-85b0-106a7e092803.png)

**Comment by yuvipanda** [comment]
Hmmm I thought we had turned off this sqlite history thing in notebook? We don't need it and sqlite on nfs is a pain..

**Comment by ryanlovett** [comment]
Looks to be related to notebook signing rather than history, but I think we can store the signatures [in memory](https://nbformat.readthedocs.io/en/latest/api.html#nbformat.sign.MemorySignatureStore) rather than in sqlite.

**Comment by ryanlovett** [comment]
Hopefully fixed by #1035.
