### ISSUE TITLE
Create github account for use by circleci to deal with github api access limits

### ISSUE THREAD

**Issue by felder** [berkeley-dsep-infra/datahub#1048]
Github only allows 60 unauthenticated api requests per hour.
https://developer.github.com/v3/#rate-limiting

We can fix this by making authenticated requests.  To do so we need a dummy github account to generate a personal access token.  That token can then be supplied via a circleci environment variable called GITHUB_PAT.

Account password should be stored in support/secrets.yaml

**Comment by ryanlovett** [comment]
Just documenting that a single call to devtools::install_github reduced my `curl -s https://api.github.com/rate_limit | jq .rate.remaining` from 55 to 52. We have 37 install_github currently between the datahub and r deployments.

A short term workaround would be to remove some of them from the datahub deployment image.

**Comment by yuvipanda** [comment]
This has stopped being as much of an issue since we mostly install R packages from packagemanager.rstudio.com.
