### ISSUE TITLE
Request two python packages for "Physics 188/288"

### ISSUE THREAD

**Issue by ybh0822** [berkeley-dsep-infra/datahub#1073]
**Which package do you want installed?**
1. https://github.com/HerculesJack/assignment-1910 
2. getdist (https://getdist.readthedocs.io/en/latest/)

**Which class will use this package?**
Physics 188/288 (Bayesian Data Analysis and Machine Learning for Physical Sciences, https://classes.berkeley.edu/content/2019-fall-physics-188-001-lec-001)

**Which semester will this package be used for?**
Fall 2019

Thanks a lot!
Sincerely,
Byeonghee

**Comment by felder** [comment]
@ybh0822 can you please release item 1 via pypi so we can simply perform a pip install?

**Comment by ybh0822** [comment]
Actually, this package is not yet ready to be released via pypi. Would it be possible to install them by running install.sh? Sorry for the inconvenience :(

**Comment by ybh0822** [comment]
Sorry to bug you again :( Would it be possible to install the packages from https://github.com/HerculesJack/assignment-1910 ?
We hope to use them in an assignment that will be released this week. Thank you again for your help!

**Comment by ybh0822** [comment]
Thanks a lot for responding to my request! But it seems that the final deployment test has failed...

**Comment by ryanlovett** [comment]
@ybh0822 This is done. The install script for assignment-1910 doesn't install the software -- it builds it in place -- so I've put the build directory in /srv/app/venv/assignment-1910.

**Comment by ryanlovett** [comment]
@ybh0822 That failure was actually a manual stoppage of a secondary deployment, where the prior one had succeeded.

**Comment by ybh0822** [comment]
Thanks! I guess I should wait until tomorrow to see if I can load those packages! Thanks a lot for your help :)
