### ISSUE TITLE
Request python package otter-grader for class Data 88

### ISSUE THREAD

**Issue by chrispyles** [berkeley-dsep-infra/datahub#1108]
**Which package do you want installed?**

otter-grader==0.0.7

**Which class will use this package?**

[Data 88](https://classes.berkeley.edu/content/2019-fall-data-88-001-sem-001)

Include a link to appropriate entry in https://classes.berkeley.edu/ if available. If not, please mention class name & instructor.

**Which semester will this package be used for?**

Fa 19 - needed ASAP for a notebook that deploys Tue 10/15

This helps us clean up unused packages after a term ends.

**Any additional information we should know about?**

**Comment by chrispyles** [comment]
Forgot to add a couple dependencies for otter-grader. Can you please also install gofer-grader==1.0.3 and nb2pdf==0.0.1

**Comment by yuvipanda** [comment]
@chrispyles can you mark them as dependencies in your package via setup.py instead? That will be much cleaner.

**Comment by chrispyles** [comment]
OK, pushed to PyPI. Can you please update to otter-grader==0.0.8?

**Comment by chrispyles** [comment]
Actually I am debugging one of the scripts in a dependency so please don't update yet. Thanks!

**Comment by chrispyles** [comment]
Debugged! Please install otter-grader==0.0.10. Sorry for all the confusion!

**Comment by ryanlovett** [comment]
Fixed by #1112.
