### ISSUE TITLE
data100 hub logs filling up hub disk

### ISSUE THREAD

**Issue by yuvipanda** [berkeley-dsep-infra/datahub#1125]
data100 only has a 4G disk for the hub than a 40G. This makes the logs fill up the disk every other month or so.

We should make the disk bigger, and also gzip it by default

**Comment by felder** [comment]
@yuvipanda

Alas, azure does not support resizing pvcs that are currently attached.
https://github.com/kubernetes/kubernetes/issues/68427

So a resize cannot be done without downtime.

We should gzip the logs now and resize the pvc over winter break (we have to re-provision the cluster anyway to move the subscription over to the new portal) if we're still running data100 on azure.

**Comment by andyzhangx** [comment]
azure disk don't support resize on the fly, here is the workaround as I summarized, there is still downtime(could be within 2min), https://github.com/andyzhangx/demo/blob/master/linux/azuredisk/azuredisk-sizegrow.md

**Comment by yuvipanda** [comment]
We made the data100 base disk larger, and that works out ok. It's also no longer on azure (yay)
