### ISSUE TITLE
Request two python packages for PHYS188

### ISSUE THREAD

**Issue by ybh0822** [berkeley-dsep-infra/datahub#1131]
**Which package do you want installed?**
1. tensorflow_probability (https://www.tensorflow.org/probability/install)
2. tensorflow_hub (https://www.tensorflow.org/hub/installation)

**Which class will use this package?**
Physics 188/288 (Bayesian Data Analysis and Machine Learning for Physical Sciences, https://classes.berkeley.edu/content/2019-fall-physics-188-001-lec-001)

**Which semester will this package be used for?**
Fall 2019

**Any additional information we should know about?**
Would it be possible to have them installed by 11/1? 
Thank you very much for your help and have a great day. 
Sincerely,
Byeonghee

**Comment by felder** [comment]
@ybh0822 these packages conflict with tensorflow 1.3.0 which is required by another group.

I'm going to ask them if it's ok for me to update tensorflow from 1.3.0 to 2.0.0 so that I can install these.  Failing that, I'll ask about 1.7.0, however it seems that version 1 and version 2 of tensorflow differ greatly.  Will you be able to work with tensorflow 1.x?

**Comment by felder** [comment]
@ybh0822 email sent to inquire about upgrading.  I'll let you know when I hear back.

**Comment by felder** [comment]
@ybh0822 They replied and said that upgrading to version 2 was ok, so I'll work on that shortly.

**Comment by ybh0822** [comment]
That sounds perfect! I really appreciate your help :)

**Comment by ybh0822** [comment]
I checked that tensorflow 1.15.0 works well for me, so I think it's better to have v1.15.0 instead of v2.0 since tf1 and tf2 functions differ.
Thanks a lot!
Byeonghee

**Comment by felder** [comment]
@ybh0822 I'm sorry, I spent the afternoon getting this to build and deploy.  I do not have more time to switch the version.  This is going to have to wait until next week.

**Comment by ybh0822** [comment]
Okay :) Thank you for your help!

**Comment by felder** [comment]
Tensorflow is now version 1.15.0.

**Comment by ybh0822** [comment]
That's perfect, thanks a lot for your help and consideration!
