### ISSUE TITLE
Typo in 8.3x lab 4

### ISSUE THREAD

**Issue by fqzbdkh** [berkeley-dsep-infra/datahub#1143]
in 8.3X lab4, the euclidean distance formula is sqrt((x1-x2)^2 - (y1-y2)^2), when it should be sqrt((x1-x2)^2 + (y1-y2)^2)

**Comment by felder** [comment]
@fqzbdkh This is not a datahub operational issue.  

You should, instead, file this issue here:
https://github.com/data-8/materials-x18/issues
