### ISSUE TITLE
Request R package lfe for class EEP 118

### ISSUE THREAD

**Issue by ericvd-ucb** [berkeley-dsep-infra/datahub#1154]
**Which package do you want installed?**
lfe 

It turns out it is on the r.datahub but not on the main datahub

**Which class will use this package?**

EEP 118

Include a link to appropriate entry in https://classes.berkeley.edu/ if available. If not, please mention class name & instructor.

**Which semester will this package be used for?**

Fall 19 and then Spring 20.. potentially its taught every semester

This helps us clean up unused packages after a term ends.

**Any additional information we should know about?**

**Comment by yuvipanda** [comment]
Could this class be taught using the R hub long term?

**Comment by felder** [comment]
@yuvipanda should I go ahead and add this, or are you waiting on a response from @ericvd-ucb ?

**Comment by ericvd-ucb** [comment]
Yes - I told them to use the R hub, but if possible could you go ahead and add it in case they cant redirect their whole class?

**Comment by yuvipanda** [comment]
@felder I think we should add this for now, but develop a way to move all the R classes to the R hub for the next semester

**Comment by felder** [comment]
Deployed to prod.
