### ISSUE TITLE
Bump otter to 0.1.6

### ISSUE THREAD

**Issue by chrispyles** [berkeley-dsep-infra/datahub#1169]
Hey, sorry about this, but we left out a necessary function when we removed the gofer dependency from otter-grader that we only just caught; is it possible to bump it to 0.1.6?

**Comment by yuvipanda** [comment]
Hey @chrispyles!

It'll probably be easier if you can make a PR updating it: https://github.com/berkeley-dsep-infra/datahub/blob/staging/deployments/datahub/images/default/requirements.txt#L114

Thanks!

**Comment by chrispyles** [comment]
Done!
