### ISSUE TITLE
Request R packages on R hub for class EEP 118

### ISSUE THREAD

**Issue by ericvd-ucb** [berkeley-dsep-infra/datahub#1198]
**Which package do you want installed?**
lmSupport
chron
quantmod
lfe
multcomp

**Which class will use this package?**
EEP 118 - Spring 2020
Sofia Villas-Boas
https://classes.berkeley.edu/content/2018-spring-envecon-c118-001-lec-001

Include a link to appropriate entry in https://classes.berkeley.edu/ if available. If not, please mention class name & instructor.

**Which semester will this package be used for?**
Spring 2020 ( but continuing) 

This helps us clean up unused packages after a term ends.

**Any additional information we should know about?**

**Comment by yuvipanda** [comment]
I think this is present now.
