### ISSUE TITLE
Spring 2020 cluster migration

### ISSUE THREAD

**Issue by yuvipanda** [berkeley-dsep-infra/datahub#1202]
This issue tracks the things we need to do to move datahub and friends to a new cluster.

- [x] Upgrade k8s master
- [ ] Upgrade nodepools
- [x] Upgrade to helm 3 (https://helm.sh/blog/migrate-from-helm-v2-to-helm-v3/)
- [x] Move HTTPS provisioning to https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1539
- [ ]

**Comment by yuvipanda** [comment]
k8s master has been updated with 0 downtime (since we are on a regional cluster), just by clicking the button in the console.

**Comment by felder** [comment]
We also want to:

- [ ] retrieve logs from old data100 setup
- [ ] setup vm for data100 grader
- [ ] coordinate to patch and reboot data8x grader
- [ ] clear space on / for nfsserver
- [ ] setup monitoring on nfsserver (diskspace!)

**Comment by yuvipanda** [comment]
We did most of these things, but never documented them here :(
