### ISSUE TITLE
Data100 Jupyter pod pre-provisioning

### ISSUE THREAD

**Issue by wwhuang** [berkeley-dsep-infra/datahub#1224]
Hi, 

I was wondering how pre-provisioning pods is going to work this semester. 

Our schedule has assignments due on Monday nights, so I'm expecting heavy usage Saturday, Sunday, and Monday. We have roughly 1200 students, compared to the ~900 last semester. There might be many more users for the first few weeks, since I believe waitlisted students do the first few assignments. 

Thanks, 
Will

**Comment by yuvipanda** [comment]
I think our autoscaling has caught up, and this isn't a problem anymore.
