### ISSUE TITLE
Request update for python package tensorflow v2.1.0 for class data-x

### ISSUE THREAD

**Issue by OrthoDex** [berkeley-dsep-infra/datahub#1226]
**Which package do you want installed?**
tensorflow v2.1.0  (upgrade)
Data-X is upgrading it's assignments to use tensorflow v2.1.0 from the current v1.15.0 in datahub.

**Which class will use this package?**
Data-X : https://data-x.blog/

https://classes.berkeley.edu/content/2020-spring-indeng-135-001-lec-001

Include a link to appropriate entry in https://classes.berkeley.edu/ if available. If not, please mention class name & instructor.

**Which semester will this package be used for?**
Spring 2020

This helps us clean up unused packages after a term ends.

**Any additional information we should know about?**

**Comment by felder** [comment]
@ybh0822 I'd like to bring your attention to this issue, since I worked with you on issue #1131 

As I understand it, tensorflow v2 is very different from tensorflow v1.  Is this change going to cause issues for your course?

**Comment by ybh0822** [comment]
Thanks for the heads-up! For PHYS288, everything is written in terms of v1, but I think there are ways to use tf1 functions in tf2, so it should be okay.

**Comment by felder** [comment]
@ybh0822 ok.  In which case we're going to move forward with the upgrade.
