### ISSUE TITLE
Request latex package miktex

### ISSUE THREAD

**Issue by nnpok** [berkeley-dsep-infra/datahub#1242]
**Which package do you want installed?**
Latex package miktex

**Which class will use this package?**
ph142, Mi-Suk Kang Dufour

Include a link to appropriate entry in https://classes.berkeley.edu/ if available. If not, please mention class name & instructor.

**Which semester will this package be used for?**
SP20 and onwards

This helps us clean up unused packages after a term ends.

**Any additional information we should know about?**

**Comment by yuvipanda** [comment]
Can you provide some more detail about what you mean by 'latex package'? I'm extremely unfamiliar with latex...

**Comment by felder** [comment]
If possible, it'd be better if we can use a package that's available via apt from the system repositories.  Texlive maybe?  I'm not very familiar with LaTex either.

**Comment by nnpok** [comment]
That makes three of us :(
