### ISSUE TITLE
Package request: daft/ pyMC3 on phy151 server.

### ISSUE THREAD

**Issue by ybh0822** [berkeley-dsep-infra/datahub#131]
Hi! Would you help us to deploy the following packages on the server?

pyMC3 (https://github.com/pymc-devs/pymc3), 
daft (http://daft-pgm.org/). 

Thanks in advance!
Byeonghee

**Comment by yuvipanda** [comment]
@gunjanbaid @henchc can either of you take charge of this? Not sure who the phy151 folks are working with already.

**Comment by gunjanbaid** [comment]
Yes, I can add these. @ybh0822 when do you need these ready by?

**Comment by ybh0822** [comment]
Thanks! It seems like that you already installed them on the server.

**Comment by gunjanbaid** [comment]
Yes, these should be available on datahub!
