### ISSUE TITLE
Shut down Datahub for Data 8 midterm

### ISSUE THREAD

**Issue by scottjlee** [berkeley-dsep-infra/datahub#1360]
Due to recent developments with COVID-19, we will be holding an online midterm exam (on Gradescope) on Friday 3/13 from 7:10-10:30pm (including DSP times). Is it possible to shut down data 8's Datahub during this time, so that students don't have access to any course materials or Datahub in general?

We also noticed on the admin panel of Datahub, there is a big red "shutdown hub" button--will pressing this accomplish what we want, and is Datahub able to be brought back online with the same button afterwards?

**Comment by yuvipanda** [comment]
@scottjlee Unfortunately, many courses use datahub, not just data-8, so it isn't possible to shut down. Moreover, the R and Julia hubs also use the same home directories, so students can access those easily - and we can not shut those down either. Moreover, as I'm sure you already know, there's nothing preventing students from downloading and accessing the material at home...

I would recommend not pressing the big red 'shutdown hub' button :D I suspect it will cause a few minutes disruption, and then the hub just restarts.

**Comment by scottjlee** [comment]
Got it, thanks! We'll hold the exam assuming students can access the Hub.
