### ISSUE TITLE
16A/B public materials addition

### ISSUE THREAD

**Issue by firebolt55439** [berkeley-dsep-infra/datahub#1363]
Hi guys — I'm a software TA for 16B and was hoping to discuss potentially moving over all Jupyter-related items (lab, homework, etc.) to Datahub. Specifically, we were hoping we could add our public materials to Datahub as well so that students could access them (just like Data 8 has).

Also, we don’t want to overburden Datahub compute resources (between us, we have 1600 students, could be a hundred at any given time worst-case), so let us know if this isn't feasible.

Do you think this would be workable?

**Comment by yuvipanda** [comment]
Heya! @firebolt55439 I think we should be able to do this. If you can give me:

1. Expected resource usage (RAM and CPU?). You can test this out by running a sample notebook, and noting the RAM usage in the notebook interface' upper left corner
2. Any particular libraries / etc you need added?

There's no content in datahub itself. Usually it's in a GitHub repository, and pulled in via [nbgitpuller links](nbgitpuller links). You can see links like that in http://data8.org/fa19/ for example. You can self serve these links by creating them at nbgitpuller.link, and should already work.

Hope this is useful!

**Comment by firebolt55439** [comment]
Absolutely, I'll post those on this thread ASAP. Am currently moving out of housing a bit early, but I will follow-up by end of day with any needed libraries and an estimate for resource usage.

**Comment by yuvipanda** [comment]
Thanks, @firebolt55439. 

I'll try make sure everything is sorted by the weekend.

**Comment by neeleshkr** [comment]
Hello, I'm the 16A Software TA also working on the project . For one of the circuit simulation notebooks we have, the libraries required are as follows:

1. `import numpy`
2. `from matplotlib import pyplot`
3. `import sympy`
4. `import sys`
5. `import lcapy` (and if needed for a particular local installation, we pip install it with ` !{sys.executable} -m pip install --user https://github.com/mph-/lcapy/zipball/master`
6. `import shutil`
7. `import urllib.request`
8. `import base64`
9. `from urllib.parse import urlencode, quote_plus`
10. `from IPython.display import Image`

Please let us know if you need anything else, thanks for your help!

**Comment by firebolt55439** [comment]
@yuvipanda Also, I couldn't find the CPU usage, but the RAM usage was in the 212 - 276 MB range when I tried it.

**Comment by yuvipanda** [comment]
@firebolt55439 that sounds good, re: RAM. I think the default datahub usage limits should suffice.

@neeleshkr it looks like everything you need should already be installed in datahub.berkeley.edu, except maybe lcapy. Can you confirm?

/cc @ericvd-ucb who might be interested.

**Comment by firebolt55439** [comment]
That sounds about right — lcapy is likely the one dependency that's missing.

**Comment by yuvipanda** [comment]
@firebolt55439 @neeleshkr I installed lcapy (with #1364 and #1367), lmk if everything works now.

**Comment by firebolt55439** [comment]
That did the trick @yuvipanda! Thank you for your help!

**Comment by firebolt55439** [comment]
Will start moving Jupyter stuff over as soon as we can.

**Comment by yuvipanda** [comment]
Awesome, @firebolt55439, glad it is all working out.

I think we have everything set up, so I'll close this now.
