### ISSUE TITLE
Heads up on nfs-mounter and gke  upgrade

### ISSUE THREAD

**Issue by dirkcgrunwald** [berkeley-dsep-infra/datahub#1370]
Just a heads up that your nfs-mounter hub/templates/nfs-mounter.yaml is using a betav1 daemonset specification. GKE recently sent an announcement saying these will no longer work in v1.16 and need to be upgraded. There was a long list of other deprecations but most didn't seem to impact our setup.

I'm using your same method and the only change that I've seen is that the daemonset now needs an explicit 'selector' set. According to https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/ this should match the selctor in the pod template.

When I did this on our setup, the nfs-mounter failed on new nodes. I haven't had a chance to circle back and figure out why.

The automatic upgrades that will require this change will start on april 9th.

**Comment by yuvipanda** [comment]
Awesome! Thank you for letting us know - my goal is to remove nfs-mounter from our cluster completely by then. If not, I'll try change this.

Thanks!

**Comment by dirkcgrunwald** [comment]
Btw, I was incorrect in any difficulty of this -- I had accidentally removed a node-selector that caused problem (i.e. shot myself in the foot)

What is your future strategy for shared files? The nfs-mounter option has worked well, but it has required using an Ubuntu cluster, which I'm assuming is a little less secure.

Because of limited time, I didn't have the option of evaluating the performance / scalability trade-off of using a k8s NFS server/provisioner vs. external NFS server vs. using the Google filer. We typically have 30-200 users which is not a huge concurrent demand.
