### ISSUE TITLE
Add env variable on 8X Hub

### ISSUE THREAD

**Issue by chrispyles** [berkeley-dsep-infra/datahub#1386]
Need to add `GOFER_LOGGING_ENDPOINT` as an environment variable on the 8X Hub. I've emailed @yuvipanda and @felder the secret.

**Comment by yuvipanda** [comment]
I've suggested to @chrispyles an alternate solution that I think is more robust. Hopefully that can be implemented without too much trouble.

**Comment by chrispyles** [comment]
Resolved with @yuvipanda's suggestion
