### ISSUE TITLE
Data 100 autograder shared folder access

### ISSUE THREAD

**Issue by wwhuang** [berkeley-dsep-infra/datahub#1401]
Hi, 

I'm trying to give the data100 autograder access to the data100 shared folder, but can't quite figure out how it works. I tried adding the shared folder according to tutorials I found online, but it can't find the mount path. What does the VolumeMountHack do, and does the autograder need any special permissions to access the shared folder?  

Thanks, 
Will

**Comment by yuvipanda** [comment]
Thanks for opening this issue here!

Do you wanna give the data100 autograder *pods* access to the shared folder, or the VM? Both are possible but quite different.

**Comment by wwhuang** [comment]
I want to give the autograder pods access to the shared folder.

**Comment by wwhuang** [comment]
Here's the spec I'm using. It appears that it does try and mount the volume, but errors out b/c it can't find it.: 

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ name }}
  namespace: data100-grader
  labels: {"heritage":"Pandas-Grader"}
spec:
  ttlSecondsAfterFinished: 0
  backoffLimit: 0
  parallelism: {{ parallelism }}
  completions: {{ num_jobs }}
  template:
    spec:
      containers:
      - name: {{ name }}
        image: wwhuang/jhub-gofer:latest
        command: [
          "python", "worker.py", 
          "--api-url", "{{ api_addr }}"]
        resources:
          requests:
            memory: "512M"
          limits:
            memory: "2.25G"
        volumeMounts:
          - name: home
            mountPath: /home/jovyan/shared
            subPath: _shared
      restartPolicy: Never
      imagePullPolicy: Always
      nodeSelector:
        hub.jupyter.org/pool-name: beta-pool
      tolerations:
        - key: "hub.jupyter.org/dedicated"
          operator: "Equal"
          value: "user"
          effect: "NoSchedule"
        - key: "hub.jupyter.org_dedicated"
          operator: "Equal"
          value: "user"
          effect: "NoSchedule"

**Comment by wwhuang** [comment]
Link to file with the spec: 

https://github.com/DS-100/Pandas-Grader/blob/master/pandas_grader/app/k8s.py

**Comment by yuvipanda** [comment]
@wwhuang you also need to provide a `volumes` key in your pod specification, in addition to `volumeMounts` in your container specification. https://kubernetes.io/docs/tasks/configure-pod-container/configure-volume-storage/ has an example.

I tried to take a stab at it in https://github.com/DS-100/Pandas-Grader/pull/15. That should give you a general idea of what should happen.

As noted there, this is a hack. Should use https://kubernetes.io/docs/concepts/storage/persistent-volumes/ instead, but that is an easy conversion

**Comment by yuvipanda** [comment]
I don't think pandas-grader is still used.
