### ISSUE TITLE
Upgrade version of notebook package across all hubs

### ISSUE THREAD

**Issue by yuvipanda** [berkeley-dsep-infra/datahub#1453]
The `notebook` python package is at 6.x now. We have been running a full version behind (5.x) for a while now. Time to upgrade!

We should do this in a staggered fashion, one hub at a time.

- [x] prob140
- [x] r
- [ ] datahub
- [ ] julia
- [ ] data8x
- [ ] workshop
- [x] data102
- [ ] stat89a
- [ ] template
- [ ] desktop-test

**Comment by felder** [comment]
r hub upgraded

**Comment by felder** [comment]
data102 is running notebook 6.0.0

**Comment by felder** [comment]
stat89a doesn't build if I specify a new notebook version in environment.yml

**Comment by yuvipanda** [comment]
This is now done, with #1667
