### ISSUE TITLE
Migrate storage from lvm and zfs to a single google persistent disk per filesystem

### ISSUE THREAD

**Issue by felder** [berkeley-dsep-infra/datahub#1455]
- [ ] Cull existing files according to our storage policy #1633 
- [x] Sync existing files to new storage
- [x] provision new resized (e2-standard-2) VM running ubuntu 20.04 LTS
- [x] schedule downtime
- [x] turn off hub for all users, perform final sync, and reconfigure hub to use new storage
- [x] decommission old storage and VM

**Comment by yuvipanda** [comment]
I've moved the following hubs to their own 2T disk:

- eecs
- data102
- stat89a
- buds-2020
- workshop.

There's 1.7T left there now, which might be a bit too much :| But I expect big onramps for eecs, so it should be ok.

**Comment by felder** [comment]
Old server nfsserver1 deleted, old storage deleted, and static IP released.

**Comment by yuvipanda** [comment]
I think we're done here! \o/

**Comment by yuvipanda** [comment]
Thanks for making all this happen, @felder
