### ISSUE TITLE
Configure Auth for BUDS Hub

### ISSUE THREAD

**Issue by chrispyles** [berkeley-dsep-infra/datahub#1529]
The `buds-2020` hub needs auth configured. There are three options here:

* use dummy auth (least preferable)
* use Google OAuth and whitelist external student email addresses (which are associated with Google accounts)
* use bCourses auth (probably most complicated)

Dummy auth is the least secure and is probably not a good idea given that a campus course (Data 6) will also be running on the BUDS hub. I think Google OAuth is probably the way to go given that it has the lowest setup cost and will cover the edge cases we need to handle in a secure manner.

**Comment by yuvipanda** [comment]
Yep, let's do google auth with whitelist.
 Do  you have list of addresses yet?

**Comment by chrispyles** [comment]
Just forwarded you the thread with the list @yuvipanda

**Comment by ericvd-ucb** [comment]
im fine with google.... someday somebody can explain to me why the main datahub is on canvas but not others... just so im clued in?

**Comment by yuvipanda** [comment]
@ericvd-ucb it needs coordination with RTL, we don't have direct perms to do that. R, etc are also using bcourses. I'll start an issue to make things uniform
