### ISSUE TITLE
CalNet sponsored guest doesn't get datahub access

### ISSUE THREAD

**Issue by surajrampure** [berkeley-dsep-infra/datahub#1582]
I added a student who had graduated but was completing an incomplete as a CalNet sponsored guest, using their @gmail.com email account. I added them to the class (Data 100 Summer 2020) on bCourses and they confirmed that they were able to see it in their dashboard. However, when logging onto data100.datahub.berkeley.edu, they said they were presented with the message "domain not authorized". 

Earlier I added them with their @hotmail and that, predictably, also didn't work.

**Comment by felder** [comment]
We think that #1574 should solve this.

**Comment by felder** [comment]
@surajrampure data100 has been switched to use bcourses for auth.

Can you please see if the sponsored guest can now login?

**Comment by surajrampure** [comment]
They said it works now!

**Comment by felder** [comment]
Great!
