### ISSUE TITLE
Some data100 admins are being demoted upon login

### ISSUE THREAD

**Issue by felder** [berkeley-dsep-infra/datahub#1584]
@surajrampure added a few tutors as admins to data100 for the summer.  After deploying the new admin credentials to staging and prod, we can verify that the users in question are marked as admins.

However, when these users login they are demoted from admin to student.  Similarly, if these users are manually promoted within the web interface we see them being demoted again upon login.

**Comment by ryanlovett** [comment]
If the user is listed as a student in a profile course, any admin privileges [will be revoked](https://github.com/berkeley-dsep-infra/datahub/blob/staging/hub/values.yaml#L193). Is there a chance the user was in the previous data100 course which is [still in the config](https://github.com/berkeley-dsep-infra/datahub/blob/staging/deployments/data100/config/common.yaml#L17)?

**Comment by felder** [comment]
@surajrampure ok, hopefully this issue is fixed now.

Can you please confirm?

**Comment by surajrampure** [comment]
Yep, I asked two people and they both said it works. Thanks for the help!

**Comment by felder** [comment]
Hurray!
