### ISSUE TITLE
JupyterHub admin access for Data8X Hub

### ISSUE THREAD

**Issue by kvah** [berkeley-dsep-infra/datahub#1596]
Hi Jon @felder,

We have a new student on the OLS team that needs admin access for the 8x hub:

Andrei Caprau
edX-id: acaprau
github: acaprau

8.1: 0e7433ca5642cb41432e49f5353feaed
8.2: 81da7e07167fc27429baf36e4a71ea78
8.3: e3ec379e8ca696ea7e815f667189942a

-David Yi

**Comment by felder** [comment]
Done.
