### ISSUE TITLE
Request increased memory for LING 188

### ISSUE THREAD

**Issue by geoffbacon** [berkeley-dsep-infra/datahub#1622]
Could we double the memory on datahub for [LING 188](https://classes.berkeley.edu/content/2020-summer-linguis-188-001-lec-001)? This course runs until August 14th. Let me know if there's more information I can provide, or if I can make the PR.

**Comment by ryanlovett** [comment]
Hey @geoffbacon , yes, we've just documented this at https://docs.datahub.berkeley.edu/en/latest/admins/howto/course-config.html. There are examples in the various deployments, e.g. [datahub](https://github.com/berkeley-dsep-infra/datahub/blob/staging/deployments/datahub/config/common.yaml#L23), [r](https://github.com/berkeley-dsep-infra/datahub/blob/staging/deployments/r/config/common.yaml#L21). Just let us know if the docs can be improved.

**Comment by geoffbacon** [comment]
Thanks @ryanlovett! The docs are clear.
