### ISSUE TITLE
Request python package cvxpy for class EECS127/227a

### ISSUE THREAD

**Issue by matteociccozzi** [berkeley-dsep-infra/datahub#1631]
**Which package do you want installed?**
cvxpy

https://www.cvxpy.org

**Which hub do you want it installed on?  For example r.datahub, datahub, data100.datahub, etc.**
DataHub

**Which class will use this package?**
EECS127

Include a link to appropriate entry in https://classes.berkeley.edu/ if available. If not, please mention class name & instructor.
https://classes.berkeley.edu/content/2020-fall-eecs-127-001-lec-001

**Which semester will this package be used for?**
Fall 2020

**Comment by yuvipanda** [comment]
Thanks for opening this request, @matteociccozzi! This should be available once https://github.com/berkeley-dsep-infra/datahub/pull/1632 gets merged.
