### ISSUE TITLE
Put eecs hub on its own disk

### ISSUE THREAD

**Issue by yuvipanda** [berkeley-dsep-infra/datahub#1635]
The EECS hub has been live for like a few months, and already has 100G of data usage. I think it'll end up being pretty active, and we should put it in its own home directory disk, so it can expand / contract on its own.

**Comment by felder** [comment]
@yuvipanda be aware that google persistent disks cannot be shrunk.  "Contracting" in this context means provisioning new storage with the reduced amount and performing a full migration.

**Comment by yuvipanda** [comment]
@felder ty! yeah, if we ever wanna shrink it we'd have to do the whole copy dance again. My hope is that it can sort of remain at a constant level, with archivals keeping pace with new users.

**Comment by yuvipanda** [comment]
I've created a 4TB 'balanced' ssd disk, with default options: `sudo mkfs.xfs /dev/sdg`. Using XFS so we can play with user quotas later.

**Comment by yuvipanda** [comment]
Added fstab entry: `/dev/sdg /export/eecs-homes-2020-07-29  xfs     inode64,prjquota        0       0`

**Comment by yuvipanda** [comment]
There's now an rsync running in a tmux under root.

**Comment by yuvipanda** [comment]
After fiddling around a bit, I instead made a 2T balanced-ssd disk (see #1636 for why), and am gonna put all non-datahub-hubs on it, including EECS. Currently, each user seems to be using about ~400M. At upto 512MB per user, this supports ~8k users, so we should be good - especially if we can actually set quotas! Which we should.
