### ISSUE TITLE
Physics 188/288 setup for Jupyterhub

### ISSUE THREAD

**Issue by ybh0822** [berkeley-dsep-infra/datahub#1669]
**Which hub do you want it installed on?  For example r.datahub, datahub, data100.datahub, etc.**
datahub

**Which class will use this package?**
Physics 188/288 (https://classes.berkeley.edu/content/2020-fall-physics-188-001-lec-001)

**Which semester will this package be used for?**
Fall 2020

**Any additional information we should know about?**
We plan to run the assignments in the Data8 IPython Jupyter Notebook environment provided by datahub.berkeley.edu, as we did in the previous year. As for the resources, 1GB RAM is usually enough, but we need **2GB RAM** for some assignments. Below I listed the external packages installed on datahub last year at my request. Thank you for your help!

**Which package do you want installed?**
umap (https://umap-learn.readthedocs.io/en/latest/index.html)
hdbscan (https://hdbscan.readthedocs.io/en/latest/)
getdist (https://getdist.readthedocs.io/en/latest/)
daft (http://daft-pgm.org/)
corner (http://corner.readthedocs.io/en/latest/install.html)
emcee (http://dfm.io/emcee/current/user/install/)

**Comment by yuvipanda** [comment]
Apologies for the late response, @ybh0822! Everything you need should still be on datahub.berkeley.edu. Let us know when you need the 2GB RAM and we can set it up at that time.

Thanks!
