### ISSUE TITLE
RStudio terminal does not have a complete PATH

### ISSUE THREAD

**Issue by chrispyles** [berkeley-dsep-infra/datahub#1670]
When using the terminal in RStudio on r.datahub, I cannot use very many commands except those built-in to bash because the `PATH` environment variable cannot be found. Here is an example output from the RStudio terminal:

<img width="879" alt="Screen Shot 2020-08-10 at 11 11 33 PM" src="https://user-images.githubusercontent.com/40970945/89863387-da0e4b00-db5e-11ea-9435-3c741f8e4a1a.png">

```console
bash: PATH: command not found
rstudio@jupyter-cpyles:~$ pip
bash: pip: command not found
rstudio@jupyter-cpyles:~$ ls
bash: ls: command not found
rstudio@jupyter-cpyles:~$ pip
bash: pip: command not found
rstudio@jupyter-cpyles:~$ git
bash: git: command not found
rstudio@jupyter-cpyles:~$ echo $PATH
/home/rstudio/.bash_profile:
```

The first line is shown when a new terminal is opened. As you can see, only the bash profile for the dummy user is included in the `PATH` when the variable is accessed. On the regular datahub, the `PATH` is

```console
$ echo $PATH
/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/rstudio-server/bin
```

**Current workaround:** Since the file systems are the same, you can have both r.datahub and datahub open in separate tabs and use a JupyterHub terminal to do all your command line work; these changes are reflected immediately (or on refresh) in the r.datahub tab.

@ryanlovett @yuvipanda any ideas?

**Comment by yuvipanda** [comment]
@chrispyles hmm, that's weird. I'm on my RStudio in the R Datahub, and $PATH is set right. The home directory is mounted at `/home/rstudio` rather than `/home/jovyan`, but otherwise it seems ok. does restarting your server help? If not, maybe something off is happening in ~/.bash_profile or ~/.bashrc?

**Comment by chrispyles** [comment]
Ah, yes, it was something I did to my bash profile. Thanks @yuvipanda!
