### ISSUE TITLE
Give Peter Sudmant DNS access

### ISSUE THREAD

**Issue by petersudmant** [berkeley-dsep-infra/datahub#1674]
Hey @yuvipanda - can you please give psudmant DNS access? Thank you!

**Comment by yuvipanda** [comment]
This was to setup genomics.datahub.berkeley.edu. Also, it is very difficult for us to add additional folks to DNS - so I've just added the entries.

Thanks for making this all happen, @petersudmant!

**Comment by petersudmant** [comment]
Yes - brilliant. That works better!

Thank you!
