### ISSUE TITLE
Request hub for PH155A course (fall 2020)

### ISSUE THREAD

**Issue by maryhorton1261** [berkeley-dsep-infra/datahub#1687]
Hi there,

I am the GSI for PH 155A, and we would like to use DataHub this fall. It needs to support R Studio only. There are about 50 students and there will be 5 classes/assignments where R Studio is needed (through Datahub).  

**Which class will use this package?**

PH155A - Senior Research Seminar in Public Health
https://classes.berkeley.edu/content/2020-fall-pbhlth-155a-001-lec-001

**Which semester will this package be used for?**

Fall 2020

**Comment by yuvipanda** [comment]
Hello @maryhorton1261! Can you check r.datahub.berkeley.edu and let me know if that is sufficient for your needs? Thanks :)

**Comment by maryhorton1261** [comment]
Yes- something like this would work great.

**Comment by yuvipanda** [comment]
@maryhorton1261 awesome. In that case, please feel free to use r.datahub.berkeley.edu for your class. It is meant to be a generic R hub, used by many different classes that use R. Let us know if we can be of any further assistance!

**Comment by maryhorton1261** [comment]
@yuvipanda Quick question, since I have not used Datahub previously, do students create their own personal directories in this hub that others cannot see? Or is it somehow viewable to everyone? Or will a directory for this specific course appear for enrolled students that I can put data and scripts into?

**Comment by yuvipanda** [comment]
@maryhorton1261 When students log in, a 'home directory' gets created for them that others can't see. It's viewable by admins (some of the infrastructure folks, and some course student assistants - see https://github.com/berkeley-dsep-infra/datahub/blob/staging/deployments/r/config/common.yaml#L27 for list). 

For distributing data & scripts, in general we suggest using nbgitpuller.link to distribute your content (data & script) into. @ericvd-ucb usually helps folks get setup with this (or has folks who can help), maybe he can chime in?

**Comment by ericvd-ucb** [comment]
@maryhorton1261 lets connect via email - happy to walk you through some of steps - we have an instructor facing documentation guide at https://ds-modules.github.io/curriculum-guide/workflow/distributing-notebooks.html
