### ISSUE TITLE
Adding automatic log off feature for datahub

### ISSUE THREAD

**Issue by fqzbdkh** [berkeley-dsep-infra/datahub#1725]
Would it be possible to finish implementing an automatic log off feature for Jupyter sometime within the next week? 

This feature would make sure that students are logged off from their jupyter IDs when they exit all jupyter notebook of the same jupyter ID from browser window. 

The Online Learning services is planning to re-launch the data8X course on EdX within the next two days with integrated infrastructure changes, and this feature would greatly help our team since it will eliminate most of the error with hundreds of students losing lab progress.

**Comment by yuvipanda** [comment]
Sorry about how long this has taken! https://github.com/berkeley-dsep-infra/datahub/pull/1951 is ready to test to fix this. Let's set up a time (ideally early morning?) and test this out?

**Comment by yuvipanda** [comment]
This was done!
