### ISSUE TITLE
Decommission Stat89A hub

### ISSUE THREAD

**Issue by yuvipanda** [berkeley-dsep-infra/datahub#1736]
Stat89A is not offered this fall, and we can decomission the hub. Email of this is part of the ds-infrastructure mailing list.

It might wanna come back next semester. Let's just keep the files for now, and we can sort out what to do with them later?3

**Comment by felder** [comment]
@yuvipanda Since we're keeping the files would this just involve stopping the hub and removing it from continuous integration?

**Comment by yuvipanda** [comment]
@felder pretty much. you'd also run `helm delete` on the prod and staging releases, and probably release the DNS entries too.

**Comment by felder** [comment]
@yuvipanda ok I ran:

kubectl -n stat89a-staging delete pod,svc,deployments --all
helm delete stat89a-staging -n stat89a-staging
kubectl delete namespace stat89a-staging

I also modified the circle ci configs and it seems like the right thing has occurred (circle ci is ignoring stat89a).  Before I do this to prod, I just want to make sure this series steps makes sense.

**Comment by felder** [comment]
stat89a-prod deleted using similar commands as above.

Static ips removed and dns records removed.
