### ISSUE TITLE
basic auth going away, google says data8x project is affected

### ISSUE THREAD

**Issue by felder** [berkeley-dsep-infra/datahub#1776]
Hello Google Kubernetes Engine Customer,

We are writing to let you know that upstream Kubernetes open source has removed support for basic authentication in version 1.19 (v1.19). Once Google Kubernetes Engine (GKE) upgrades your clusters to v1.19, you will no longer be able to use basic authentication. You will still be able to authenticate to GKE using other methods.
What do I need to know?

Kubernetes has announced that basic authentication will no longer be available starting with Kubernetes v1.19. GKE clusters will also no longer support basic authentication as they gradually upgrade to Kubernetes v1.19:

    Clusters subscribed to the rapid release channel will begin upgrades on or after January 2021
    Clusters subscribed to the regular release channel will begin upgrades on or after March 2021.
    clusters subscribed to the stable release channel and non-release-channel clusters will be upgraded later in 2021; a reminder will be sent before these clusters are upgraded to v1.19

For more control over when an auto-upgrade can occur (or must not occur), you can configure maintenance windows and exclusions.

As the Kubernetes project evolves, old APIs and features are deprecated and eventually removed in favor of new APIs and features, which will also impact Google Kubernetes Engine. Kubernetes v1.19 will no longer allow users to authenticate to the control plane using basic authentication. Existing GKE clusters upgraded to Kubernetes v1.19 will reject connections with basic authentication.

Basic authentication has been disabled by default for new GKE clusters since GKE version 1.12 and its usage has been discouraged in the GKE hardening guide.
What do I need to do?

Migrate away from basic authentication as soon as possible, before your cluster control planes are upgraded to Kubernetes v1.19. This is to ensure your API clients can continue accessing the API server. To learn more about recommended authentication methods in GKE, see Authenticating to the Kubernetes API Server.

After you migrate to an alternate authentication method, you can disable basic authentication by running the following command:

gcloud container clusters update CLUSTER_NAME --no-enable-basic-auth

If you do not migrate away from basic authentication before upgrading to Kubernetes v1.19, basic authentication will be disabled for you as part of the upgrade process. After upgrade, you will still be able to authenticate to the cluster using alternate methods such as OAuth.

Our records indicate that you have GKE clusters with basic authentication enabled in the following project(s):

    data8x-scratch (data8x-scratch)

**Comment by yuvipanda** [comment]
I think it is enabled because our cluster was created long enough ago. I think we don't need to do anything, since we don't use it anyway.
