### ISSUE TITLE
JupyterHub Admin Access for Data8X Hub

### ISSUE THREAD

**Issue by ebaccay** [berkeley-dsep-infra/datahub#1795]
Hi @felder !

We have two new students on the OLS team who need admin access for the 8x hub. This issue is for the second student, Varun Mittal. His information is provided below:

Varun Mittal
edX-id: `varunmittal35`
GitHub: `varunmittal35`

8.1x: `af5bd207bb7fd80a602d0cf488fda336`
8.2x: `6127a516b66666622476c80e7d835705`
8.3x: `4ec74d8be97f3c5ed9addc6a724effa1`

Thanks!

-Ervin Baccay

**Comment by felder** [comment]
Done!

**Comment by fqzbdkh** [comment]
Hi @felder !

Ashley Zhang just joined the OLS team and need admin access for the 8x hub, can you add her? Her IDs are included below: 

8.1x b1b001615f9eb7254387f667569e39fb
8.2x c741d11d7f0bed9930e04276115b1a37
8.3x fd5ad8c476846392d8dfb1765d1a6ac5

Thank you! 
- Grace Li

**Comment by felder** [comment]
@fqzbdkh Done.  In the future can you open a new issue as opposed to editing a closed one?
