### ISSUE TITLE
Request dplyr package 1.0.0 for PH290W: R for Public Health

### ISSUE THREAD

**Issue by lytello** [berkeley-dsep-infra/datahub#1810]
**dplyr 1.0.0**

**r.datahub**

**PHW290W: R for Public Health**

https://classes.berkeley.edu/content/2020-fall-pbhlth-290-009-sem-009

Instructor: Will Wheeler, Lawrence Tello

**Fall 2020**

**Comment by felder** [comment]
I asked @lytello in slack to confirm that this won't interfere with PH250F/G and update the issue here.  Once done, I'll attempt to deploy.

**Comment by lytello** [comment]
Confirmed: PH250F/G is not using R as they removed all R components of the course.

**Comment by felder** [comment]
@lytello ok, I'll get to work on it.  You'll see updates in this issue as I make commits.

**Comment by felder** [comment]
@lytello I'm upgrading dplyr to 1.0.2, I hope that's ok.  Please let me know if it is not.

**Comment by felder** [comment]
Running into the github api limit.  I'll try later.  

@yuvipanda does this issue I filed for hubploy (https://github.com/yuvipanda/hubploy/issues/42) seem at all feasible?  Any other ideas for getting a github_pat into the build environment?

**Comment by felder** [comment]
After waiting for the API limits to refresh, it still no worky.  There's just too many calls to github with the addition of the new dependencies.

I'm talking with @ryanlovett to try and see if we can work around this.

**Comment by yuvipanda** [comment]
I bumped up R to 4.0 (https://github.com/berkeley-dsep-infra/datahub/pull/1824), and with it got new dplyr. I was able to work-around the issues we ran into when we last tried to do this in https://github.com/berkeley-dsep-infra/datahub/pull/1786.

**Comment by lytello** [comment]
Thank you for the quick turn around!
