### ISSUE TITLE
Request increased memory for PHYS188/288

### ISSUE THREAD

**Issue by ybh0822** [berkeley-dsep-infra/datahub#1827]
For the next assignment, we need 2GB RAM. Would it be possible to double the memory for this class? 
Thank you for your help!

Class info:
Physics 188/288 (https://classes.berkeley.edu/content/2020-fall-physics-188-001-lec-001)

**Comment by felder** [comment]
@ybh0822 I believe this is for datahub.berkeley.edu, but please specify the hub in support requests.

**Comment by felder** [comment]
@ybh0822 ok that should do it.  Please let me know if it no workie.
