### ISSUE TITLE
Install 'pymc' on datahub

### ISSUE THREAD

**Issue by kobewang1359** [berkeley-dsep-infra/datahub#1840]
Dear all,

I am with Data 102 and we need 'pymc' package installed on the server. The documentation is here: https://docs.pymc.io/

We think this can be done via running the following commands:

pip install arviz==0.6.1
pip install pymc3==3.8
pip install Theano==1.0.4

Thank you very much!

**Comment by felder** [comment]
A quick check in staging indicates higher versions of these packages are already installed.

$ pip list installed | grep -E 'arviz|Theano|pymc3'
arviz                         0.9.0
pymc3                         3.9.3
Theano                        1.0.5
