### ISSUE TITLE
Can not knit on r datahub

### ISSUE THREAD

**Issue by lytello** [berkeley-dsep-infra/datahub#1841]
**Which package do you want installed?**

I believe we need tinytex (I could be wrong) based on information from the chat. It seems like the recent bump to R 4.0 has led to this package missing. We can no longer knit documents to pdf.

**Which hub do you want it installed on?  For example r.datahub, datahub, data100.datahub, etc.**

r.datahub

**Which class will use this package?**

PHW290: R for Public Health

Include a link to appropriate entry in https://classes.berkeley.edu/ if available. If not, please mention class name & instructor.

**Which semester will this package be used for?**

Fall 2020, Instructors: Will Wheeler, Lawrence Tello

This helps us clean up unused packages after a term ends.

**Any additional information we should know about?**

**Comment by felder** [comment]
Here's what I get when I look for tinytex in r-staging:


> require("tinytex", character.only = TRUE)
Loading required package: tinytex
> find.package("tinytex")
[1] "/usr/local/lib/R/site-library/tinytex"
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04 LTS

Matrix products: default
BLAS/LAPACK: /usr/lib/x86_64-linux-gnu/openblas-openmp/libopenblasp-r0.3.8.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
 [6] LC_MESSAGES=C              LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] tinytex_0.25

loaded via a namespace (and not attached):
[1] compiler_4.0.2 tools_4.0.2    xfun_0.16     

>

**Comment by felder** [comment]
Thus tinytex appears to be installed.

**Comment by yuvipanda** [comment]
Re-opened to be more generic...

**Comment by yuvipanda** [comment]
@lytello can you tell us a little more about the error you are getting? Maybe it needs more packages than just tinytex installed in newer versions of R.

**Comment by lytello** [comment]
Knitting is inconsistent or taking longer than usual. One student had the following error, but it corrected itself the following morning:

`processing file: problem_set_3.Rmd
 |..........                                                            |  14%
 ordinary text without R code

 |.............                                                         |  19%
label: unnamed-chunk-2

Quitting from lines 60-65 (problem_set_3.Rmd)
Error in eval(expr, envir, enclos) :
 object 'non_deceptive_placebo' not found
Calls: <Anonymous> ... handle -> withCallingHandlers -> withVisible -> eval -> eval
Execution halted

No LaTeX installation detected (LaTeX is required to create PDF output). You should install a LaTeX distribution for your platform: https://www.latex-project.org/get/

 If you are not sure, you may install TinyTeX in R: tinytex::install_tinytex()

 Otherwise consider MiKTeX on Windows - http://miktex.org

 MacTeX on macOS - https://tug.org/mactex/
 (NOTE: Download with Safari rather than Chrome _strongly_ recommended)

 Linux: Use system package manager`

**Comment by ryanlovett** [comment]
Thank you @lytello. Can you identify a specific file belonging to a specific student that reproducibly fails to knit? If so, please report on ds-infrastructure@lists.berkeley.edu. (for student privacy)

**Comment by lytello** [comment]
I think these knitting issues were due to a different issue that I have resolved with students (data directories weren't correctly called in the script).

**Comment by lytello** [comment]
A situation occurred where I had to re-install TinyTex to knit a student's work. We received the following error:

`tlmgr: package repository http://ctan.math.washington.edu/tex-archive/systems/texlive/tlnet (not verified: gpg unavailable)
tlmgr install: package already present: amsmath
tlmgr install: package already present: latex-amsmath-dev
! LaTeX Error: File `amsmath.sty' not found.

! Emergency stop.
<read *> 

Error: LaTeX failed to compile problem_set_4_debug.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See problem_set_4_debug.log for more info.
Execution halted

No LaTeX installation detected (LaTeX is required to create PDF output). You should install a LaTeX distribution for your platform: https://www.latex-project.org/get/

  If you are not sure, you may install TinyTeX in R: tinytex::install_tinytex()

  Otherwise consider MiKTeX on Windows - http://miktex.org

  MacTeX on macOS - https://tug.org/mactex/
  (NOTE: Download with Safari rather than Chrome _strongly_ recommended)

  Linux: Use system package manager`

**Comment by felder** [comment]
@lytello are you able to provide steps that will reliably reproduce this issue?

**Comment by lytello** [comment]
@felder It doesn't seem like I can reliably reproduce the issue, probably because I manually installed TinyTex? However, on a related knitting issue, another student's knit is taking minutes longer than it should, but it does knit successfully. I will share with you their notebook privately!

**Comment by felder** [comment]
@lytello I have some ideas for how to approach this issue.  The first thing I'm going to try is replacing all of the installed texlive packages with system native texlive packages.  This will bring the r hub in line with how the other hubs operate.  This may be a somewhat intrusive change, but we currently believe that these packages are only used for pdf knitting.  Thus if pdf knitting continues to work (and works better) the change will probably be ok.

However, I will need your help to test this in staging since I don't want to push this to prod without said testing.  Additionally if we have some reproducible cases where pdf knitting does not work that would be very helpful as part of that testing.

I'm hoping to have some time later in the week where I can sit down and work on this.  After which I will want to schedule some time with you to test.

**Comment by lytello** [comment]
@felder Happy to help! At the moment, I don't have any other knitting issues like this, but I will keep an eye out. I think many of the students are installing tinytex again in an attempt to solve the issue.

**Comment by felder** [comment]
@lytello I have tested replacing texlive with system packages in my development environment.  The r hub image builds with these changes, but we need to test in staging.  What's your availability look like to help with this?

**Comment by lytello** [comment]
Any time Tuesday before 5 pm and Wednesday before 2pm. Does that work?

**Comment by felder** [comment]
@lytello yeah both of those days should be fine.  I'll try to message you on slack those 2 days.

**Comment by felder** [comment]
@lytello 

Using tlmgr, I installed collection-latexextra

This pulled and installed a ton of packages.  I believe it also should largely resolve the vast majority of knitting issues.

Students need to restart their servers in order to take advantage of this.  So if a student has a knitting issue, they should make sure their work is saved then:

1.  Go here:  https://r.datahub.berkeley.edu/hub/home
2.  Click the red "Stop My Server" button and wait for the button to change to "Start My Server"
3.  Click "Start My Server"
4.  Click "Launch Server"
