### ISSUE TITLE
Request python package graphviz for class L&S22

### ISSUE THREAD

**Issue by winstonyin** [berkeley-dsep-infra/datahub#1847]
**Which package do you want installed?**
graphviz

**Which hub do you want it installed on?  For example r.datahub, datahub, data100.datahub, etc.**
I assume it's the default datahub.berkeley.edu

**Which class will use this package?**
L&S22 Sense & Sensibility & Science. Instructor: Saul Perlmutter (main contact), Alison Gopnik, John Campbell

**Which semester will this package be used for?**
Spring 2021, but likely will need it yearly

**Any additional information we should know about?**
graphviz requires binaries to be installed on the server in addition to the python package, see https://graphviz.org/download/

**Comment by chrispyles** [comment]
Merged #1853 to staging which adds this package and its binary. #1854 merges the change to prod and will close this issue.
