### ISSUE TITLE
Request python packages and cli programs for BioE-131

### ISSUE THREAD

**Issue by connorbybee** [berkeley-dsep-infra/datahub#1885]
**Which package do you want installed?**
bowtie2 on conda bioconda channel
spades on conda bioconda channel

pbzip2
ArithmeticCompress

**Which hub do you want it installed on?  For example r.datahub, datahub, data100.datahub, etc.**
biology.datahub

**Which class will use this package?**
BioE131

**Which semester will this package be used for?**
Fall 2020

**Comment by felder** [comment]
@connorbybee What is ArithmeticCompress?  Can you provide a link?

**Comment by connorbybee** [comment]
Thanks for this!

Instead of ArithmeticCompress, is it possible to have the compress program installed. It is a a standard unix compression tool used with tar.

**Comment by felder** [comment]
compress (and uncompress) have installed.
