### ISSUE TITLE
No google client config found for reading in google sheets

### ISSUE THREAD

**Issue by alleanna** [berkeley-dsep-infra/datahub#1902]
https://github.com/ds-modules/MCB-32/tree/master/lab06 

Lab06 (which is now lab07) for MCB32 utilizes Reading Google Sheets from Datahub but it asking for authentication. We have the backup of saving the class data as a csv if needed since the lab is going live in a couple of days.

<img width="1069" alt="lab07error" src="https://user-images.githubusercontent.com/31870915/96056812-63324e80-0e3c-11eb-9f7a-fac98b8ebb73.png">

Thanks!

**Comment by alleanna** [comment]
<img width="868" alt="lab07_full" src="https://user-images.githubusercontent.com/31870915/96163307-98877c80-0ece-11eb-9716-5fcd47846461.png">

**Comment by alleanna** [comment]
I'm not sure if this helps but I know gspread updated the import syntax I changed 

from gspread_pandas.client import Spread to
from gspread_pandas.spread import Spread

**Comment by yuvipanda** [comment]
Ah, this looks like an issue in the module code. https://github.com/ds-modules/MCB-32/pull/16 seems to fix it. Try it out?
