### ISSUE TITLE
Shared files for BioE131

### ISSUE THREAD

**Issue by connorbybee** [berkeley-dsep-infra/datahub#1912]
The BioE131 course is using biology.datahub.berkeley.edu for genome assembly and alignment.

Is it possible to have a shared drive added for large files (~1-10 GBs)? The students would need to have read rights and the instructors would have write access.

Thanks.

**Comment by ryanlovett** [comment]
This can be done with volume mounts. Closing due to the age of the issue, but please re-open if this config is desired for a specific course. We'd need the bCourses course ID. (the number in the URL)
