### ISSUE TITLE
Request python package cvxpy for class EECS127

### ISSUE THREAD

**Issue by matteociccozzi** [berkeley-dsep-infra/datahub#1920]
**Which package do you want installed?**
cvxpy

**Which hub do you want it installed on?  For example r.datahub, datahub, data100.datahub, etc.**
datahub

**Which class will use this package?**
EECS127/227a

Include a link to appropriate entry in https://classes.berkeley.edu/ if available. If not, please mention class name & instructor.
https://inst.eecs.berkeley.edu/~ee127/fa20/

**Which semester will this package be used for?**
Fall2020, Spring2021

This helps us clean up unused packages after a term ends.

**Any additional information we should know about?**

I had this package installed this summer, we used this package in a homework two weeks ago but for some reason it gives an import error. There is a homework this week which relies on this package. Thank you!

**Comment by yuvipanda** [comment]
hey!

For EECS classes, we're encouraging folks to use eecs.datahub.berkeley.edu. It does have cvxpy - can you try that out?

**Comment by matteociccozzi** [comment]
Worked just fine thank you! I need to make a package request for eecs.datahub.berkeley.edu, can I do that here or is there another page?

**Comment by yuvipanda** [comment]
@matteociccozzi opening up #1936 is good! Thanks :)
