### ISSUE TITLE
Request R packages kableExtra, plotly, ggthemes, formattable for PH 290W: R for Public Health

### ISSUE THREAD

**Issue by lytello** [berkeley-dsep-infra/datahub#1921]
**Which package do you want installed?**

1. kableExtra
2. plotly
3.  ggthemes
4. formattable

**Which hub do you want it installed on?  For example r.datahub, datahub, data100.datahub, etc.**

r.datahub

**Which class will use this package?**

Public Health 290W: R for Public Health

Include a link to appropriate entry in https://classes.berkeley.edu/ if available. If not, please mention class name & instructor.

https://classes.berkeley.edu/content/2020-fall-pbhlth-290-009-sem-009

**Which semester will this package be used for?**

Fall 2020

This helps us clean up unused packages after a term ends.

**Any additional information we should know about?**

**Comment by yuvipanda** [comment]
There were a bunch of issues in getting this through, but all good now @lytello! Apologies for the delayed close.

**Comment by lytello** [comment]
Thank you for your hard work!! @yuvipanda @felder

**Comment by lytello** [comment]
@yuvipanda Sorry to bring this back up, is it possible to get the newest version of kableExtra (I believe it's 1.3.1)? I'm not sure if that was related to the issues you were experiencing.

**Comment by yuvipanda** [comment]
@lytello yeah, that was part of the issue - see description in #1926. 

We can try get that fixed though.

**Comment by yuvipanda** [comment]
I think this was fixed.
