### ISSUE TITLE
Request python package sklearn for class EECS127

### ISSUE THREAD

**Issue by matteociccozzi** [berkeley-dsep-infra/datahub#1936]
Which package do you want installed?
sklearn

Which hub do you want it installed on? For example r.datahub, datahub, data100.datahub, etc.
eecs.datahub

Which class will use this package?
EECS127/227a

Include a link to appropriate entry in https://classes.berkeley.edu/ if available. If not, please mention class name & instructor.
https://inst.eecs.berkeley.edu/~ee127/fa20/

Which semester will this package be used for?
Fall2020, Spring2021

This helps us clean up unused packages after a term ends.

Any additional information we should know about?
Nope.

**Comment by yuvipanda** [comment]
Thanks for opening this, @matteociccozzi! Do you think you can make a pull request to https://github.com/berkeley-dsep-infra/datahub/blob/staging/deployments/eecs/image/requirements.txt? That should help get this going faster. Thanks!

**Comment by yuvipanda** [comment]
Thanks a lot for the PR and debugging it, @matteociccozzi!
