### ISSUE TITLE
Request R package pdftools, imager for D-Lab CTAWG

### ISSUE THREAD

**Issue by brooksambrose** [berkeley-dsep-infra/datahub#1942]
**Which package do you want installed?**

`pdftools` with dependency poppler
`imager` with dependency X11

**Which hub do you want it installed on?  For example r.datahub, datahub, data100.datahub, etc.**

r.datahub

**Which class will use this package?**

[D-Lab Computational Text Analysis Working Group](https://dlab.berkeley.edu/working-groups/computational-text-analysis-working-group-ctawg)

**Which semester will this package be used for?**

Fall 2020, Spring 2021, Summer 2021

**Any additional information we should know about?**

If the Ubuntu dependencies are added, we can install the R packages ourselves.

**Comment by yuvipanda** [comment]
@brooksambrose done now with #1943! In the future, do you think you'll be able to make PRs like these yourself? Happy to review and merge :) 

And welcome!!! <3
