### ISSUE TITLE
Update admin hub IDs on 8X hub 

### ISSUE THREAD

**Issue by sideye** [berkeley-dsep-infra/datahub#1945]
Since we launched a new 8X course a couple months ago, the 8X staff's hub IDs from the new course have not been updated to be admins on the 8X hub. Making a thread below for @kvah @acaprau @ebaccay @varunmittal35 @fqzbdkh @kylemoto10 to comment their new hub IDs to become admin.

Current config is [here](https://github.com/berkeley-dsep-infra/datahub/blob/staging/deployments/data8x/config/common.yaml).

**Comment by sideye** [comment]
Please remove hub IDs of: samwu101, rroggenkemper, sauravmittal, yanay1, and manikui.

Thanks!

**Comment by kvah** [comment]
New IDS:
8.1: 57b8a1f4446a2474d577d50974e84300
8.2: 6404bc6a535a3d6de2d8823d83fd885f
8.3 ebe13f9ff075abd51b82dba85c084d94

Remove IDS:
4da3ae20c3f95786fce26c8b92d37a60
ba2c4ab02e0a25755ce903d5c376b7e2
64b9b0b2fde14942b20fe960002b38d9

**Comment by fqzbdkh** [comment]
New IDS:
8.1: 74b327432e5eb255cadf6d529101bf57
8.2: 87fba502e86ba163fe873ab00129e1ef
8.3: edc57c2ad1449d9b188d9edea333285a

Remove IDS:
461ee9f934be0a3079ba12ecc066939b
780e0c299d28f5ab0d505ec8dfffd898
ccd399c54550718cafa19b4a2e230bfc

**Comment by sideye** [comment]
New IDs:
800142d00c6dfd324853601777917b7a
7e42c2210de51307336bad6ecd3698fb
7af8a4b560d265c438354cb0b667e9fa

Remove IDs:
574b83d902c693a3ebe45fac88e498e8
dab2902831a95eb786a1f52b14717b38
2003753d84d84db85790fa8de0739eb4

**Comment by kylemoto10** [comment]
New IDs:
ab46420586cb463f422b19ee8747668c
2742155a6983300ca2feccf471debd4d
31a437b2bcf068a60c89badfb1a2e563

Remove IDs:
413fff9cb76c471fa0ccb32d7d08ace6
148bc397ac774e18a846abdb54ee2e1a
9e3318ad6da44461990e1d4e3a64986f

**Comment by acaprau** [comment]
New IDs:
945f24a55351f54e990f58b4aec45f23
29d3b143997d6101d61be6debe9ce0a7
f6e1c4e320f7032bed5f79432893d562

Remove IDs:
0e7433ca5642cb41432e49f5353feaed
81da7e07167fc27429baf36e4a71ea78
e3ec379e8ca696ea7e815f667189942a

**Comment by felder** [comment]
Made changes for the 5 people that supplied new ids.

**Comment by yuvipanda** [comment]
I'm going to close this one for now. When more folks need to be made admins, please open a new issue. Thanks!
