### ISSUE TITLE
Update gofer-submit nbextension on 8xhub

### ISSUE THREAD

**Issue by sideye** [berkeley-dsep-infra/datahub#1946]
We recently updated the `gofer-submit` nbextension to remove the 8x-audit option from the drop down, since auditing students no longer utilize this feature to receive their grades. See the (short) PR [here](https://github.com/data-8/gofer_submit/pull/2). 

@felder Can the nbextension be updated on the 8X hub to reflect these changes?

**Comment by felder** [comment]
@sideye Can you guys update the pypi package here?  https://pypi.org/project/gofer-submit/

Once you’ve released the new package there, i can bump the version in the requirements.txt:
https://github.com/berkeley-dsep-infra/datahub/blob/staging/deployments/data8x/image/requirements.txt

Then pip will install it.

**Comment by sideye** [comment]
@Yanay1

**Comment by sideye** [comment]
@felder the PyPi package has been updated to v0.4 [here](https://pypi.org/project/gofer-submit/0.4/).

**Comment by yuvipanda** [comment]
@sideye should be done in https://github.com/berkeley-dsep-infra/datahub/pull/1949. In the future, you can also just open a PR like that - should make bumps like these much faster!

**Comment by sideye** [comment]
Thank you @yuvipanda and @felder !
