### ISSUE TITLE
Student unable to open any .rmd files (r.datahub)

### ISSUE THREAD

**Issue by lytello** [berkeley-dsep-infra/datahub#1954]
After performing the fix described in  #1899 the student no longer can open .Rmd files. I haven't seen this error before and unsure of the fix. Sharing user with @felder

**Comment by felder** [comment]
@lytello I switched to the user in question and opened up the .Rmd file for problem set.  I experienced no issue doing so.

I also see no way that the fix described in #1899 should impact a students' ability to open all .Rmd files.

Can you please provide me with steps to follow to reproduce this for the student in question?

**Comment by lytello** [comment]
The problem seems to have resolved itself. Strange!
