### ISSUE TITLE
Request python package ipycanvas for class Data 94 (new class in sp21)

### ISSUE THREAD

**Issue by surajrampure** [berkeley-dsep-infra/datahub#1981]
I'd like to have ipycanvas installed on datahub.berkeley.edu for Data 94, a new class I'm teaching in sp21.

When I run `!pip install ipycanvas` in the hub, my ipycanvas code runs but no output is produced, unlike when I run things locally. I've provided screenshots for reference.

Local:
<img width="588" alt="Screen Shot 2020-11-21 at 10 41 01 PM" src="https://user-images.githubusercontent.com/10468713/99893204-34817200-2c4b-11eb-943a-64c7e687a76f.png">

On the hub:
<img width="716" alt="Screen Shot 2020-11-21 at 10 41 36 PM" src="https://user-images.githubusercontent.com/10468713/99893207-3ba88000-2c4b-11eb-8a5c-92e8f9972a87.png">

Thank you all!

**Comment by yuvipanda** [comment]
Should be done now, @surajrampure!

**Comment by surajrampure** [comment]
Looks like it works perfectly. Thanks everyone!
