### ISSUE TITLE
Investigate disk usage of 'others' home directories

### ISSUE THREAD

**Issue by yuvipanda** [berkeley-dsep-infra/datahub#1994]
Today, the disk containing homedirs for biology, eecs, prob140, etc hubs became full - bringing down a few hubs.

<img width="1421" alt="image" src="https://user-images.githubusercontent.com/30430/100496958-4ba9ed80-317e-11eb-8e71-562361b1effb.png">

I fixed it by increasing disk size to 4T. But, need to investigate what happened and how we can work with it.

**Comment by yuvipanda** [comment]
#1912  might be related.

**Comment by ryanlovett** [comment]
We're moving to Google Filestore!
