### ISSUE TITLE
DataHub GCE configuration when using GCE?

### ISSUE THREAD

**Issue by matthew-brett** [berkeley-dsep-infra/datahub#2021]
We are just thinking of setting up a pilot for a bigger JupyterHub deployment on GCE. It would really help to know exactly what the Berkeley DataHub setup uses, when it is using GCE. I mean

 * What GCE machine type for the default nodes?
 * How many machines for the default nodes?
 * What GCE machine type for the user-pool nodes?

Would you mind sharing that, so we can replicate your setup?

@choldgraf suggested I try asking here - I started at the [discourse forum](https://discourse.jupyter.org/t/gce-specifics-for-berkeley-datahub-setup).

**Comment by ryanlovett** [comment]
This is documented at https://docs.datahub.berkeley.edu/en/latest/admins/cluster-config.html?highlight=gke#kubernetes-cluster-configuration.

**Comment by matthew-brett** [comment]
Thanks!  Sorry that I missed that...

**Comment by yuvipanda** [comment]
@matthew-brett I'd also suggest looking at https://github.com/2i2c-org/pilot-hubs/tree/master/terraform
