### ISSUE TITLE
Clarification on cost of regional GKE cluster

### ISSUE THREAD

**Issue by matthew-brett** [berkeley-dsep-infra/datahub#2023]
In <https://docs.datahub.berkeley.edu/en/latest/admins/cluster-config.html> you have:

> We request our cluster masters to have highly available masters with --region parameter. This specifies the region where our 3 master nodes will be spread across in different zones. It costs us nothing extra, so we should always do it.

I think that's incorrect - at least if the JupyterHub cluster is your only cluster - because GKE offers [one free zonal cluster](https://cloud.google.com/kubernetes-engine/pricing#pricing_for_cluster_management), but you pay \$0.10 per hour for a regional cluster.

**Comment by yuvipanda** [comment]
Ah, yes - they had [changed that](https://cloud.google.com/kubernetes-engine/pricing) a few months ago. Will update docs :)
