### ISSUE TITLE
`ubuntu` container type necessary of GKE

### ISSUE THREAD

**Issue by matthew-brett** [berkeley-dsep-infra/datahub#2024]
Is it still true that you need `ubuntu` operating system containers for GKE, in order to enable NFS?

https://docs.datahub.berkeley.edu/en/latest/admins/cluster-config.html#ubuntu-operating-system

I've been using NFS with the default images for a while without problems.

**Comment by yuvipanda** [comment]
ah, the containeros images used to not have the NFS module turned on. Maybe that has changed! If so, I'll try to evaluate and change our own setup.

**Comment by yuvipanda** [comment]
It looks like they work now! https://cloud.google.com/container-optimized-os/docs/release-notes#gci-dev-53-8530-6-0. I'll migrate our nodes.

Thank you, @matthew-brett!
