### ISSUE TITLE
adding a Chemistry section to Data 100

### ISSUE THREAD

**Issue by ericvd-ucb** [berkeley-dsep-infra/datahub#2033]
Spring 21 - College of Chemistry - small grad section of Data 100 

There is a Chemistry grad class that will be teaching Data 100 - this is via a conversation with Deb Nolan.  There are something like 10 students plus instructor and GSI s.  I was advocating that we add them to Data 100. I will have a conversation with them soon, in case we need to add someone as admin will get their name.  Not sure if i i am missing something that would make this problematic

**Comment by yuvipanda** [comment]
It should be fine, as long as nobody who needs to be admin on data100 hub is also taking data100.
