### ISSUE TITLE
Kernel Error

### ISSUE THREAD

**Issue by cy5266** [berkeley-dsep-infra/datahub#2037]
Hey! I tried running the Data 8 labs from summer, and there's a Kernel Error. Restarting neither the Kernel or my laptop solved the issue, is there any way to fix this? 
If it helps, the TypeError is "_kernel_spec_manager_changed() takes 1 positional argument but 2 were given". Thank you!

**Comment by yuvipanda** [comment]
@cy5266 Can you provide a link to the notebook you used?

**Comment by cy5266** [comment]
https://datahub.berkeley.edu/user/cindycy/notebooks/materials-su20/materials/su20/hw/hw04/hw04.ipynb

Here is the jupyter notebook I was trying to run! However, the kernel also
shows an error for the other data 8 notebooks.

Thank you!

**Comment by yuvipanda** [comment]
Yep, looking into it now!

**Comment by cy5266** [comment]
Thank you!

Yuvi Panda <notifications@github.com>于2021年1月9日 周六下午6:27写道：

**Comment by yuvipanda** [comment]
@cy5266 try now? You might have to start & stop your server

**Comment by cy5266** [comment]
Hey!

It still doesn't work, unfortunately. What should I do now?

Thank you!

Best,
Cindy

**Comment by yuvipanda** [comment]
@cy5266 can you try stopping and starting your server? I see that yours has been up since before the fix was deployed

**Comment by cy5266** [comment]
Just to make sure, by stopping and starting my server, do you mean
restarting my kernel? Restarting my kernel isn't working. Is there another
way to start it again?

Thank you!

**Comment by yuvipanda** [comment]
Ah, if you go to the 'Control Panel', it will give you options for this. You can also access it with https://datahub.berkeley.edu/hub/home

**Comment by cy5266** [comment]
It works now, thank you so much for your help!

**Comment by yuvipanda** [comment]
yw! Sorry about the disruption, @cy5266!
