### ISSUE TITLE
4 GB memory for students in Astr 128 and 256

### ISSUE THREAD

**Issue by kareemelbadry** [berkeley-dsep-infra/datahub#2083]
Hi all, 

We'd like to request 4 GB of memory for students in Astro data lab (Astr 128 for undergrads, Astr 256 for grads). There are roughly 28 undergrads and 8 grads, give or take a few who might still add or drop the class. We've done this successfully the last couple years.

**Comment by kareemelbadry** [comment]
Students in both Astr 128 and 256 are reporting that they only have 1 GB RAM, not 4. Perhaps this was never implemented?

**Comment by yuvipanda** [comment]
@felder can you take a look at this?

**Comment by felder** [comment]
@kareemelbadry sorry about that.  Can you try it now?

**Comment by kareemelbadry** [comment]
Hmm, unfortunately, students are still reporting that they only have 1 GB (in both the grad and undergrad version). I had them restart their servers too.

**Comment by felder** [comment]
@kareemelbadry hmm, I may need to coordinate with you on slack to pick out some students (can't list students here, cuz FERPA)

When I view your pod, I see the resource limit is set to 4GB:

```
Jonathans-MacBook-Pro-Work:config felder$ kubectl get pod jupyter-kelbadry --namespace=datahub-prod --output=yaml | grep -A 1 -i mem
              k:{"name":"MEM_GUARANTEE"}:
                .: {}
--
              k:{"name":"MEM_LIMIT"}:
                .: {}
--
                f:memory: {}
              f:requests:
--
                f:memory: {}
            f:securityContext:
--
            f:volumeMounts:
              .: {}
--
    - name: MEM_LIMIT
      value: "4294967296"
--
    - name: MEM_GUARANTEE
      value: "4294967296"
--
        memory: "4294967296"
      requests:
--
        memory: "4294967296"
    securityContext:
--
    volumeMounts:
    - mountPath: /home/jovyan
```


To compare, here is my pod which does not have this extra ram allocated:

```
Jonathans-MacBook-Pro-Work:config felder$ kubectl get pod jupyter-felder --namespace=datahub-prod --output=yaml | grep -A 1 -i mem
              k:{"name":"MEM_GUARANTEE"}:
                .: {}
--
              k:{"name":"MEM_LIMIT"}:
                .: {}
--
                f:memory: {}
              f:requests:
--
                f:memory: {}
            f:securityContext:
--
            f:volumeMounts:
              .: {}
--
    - name: MEM_LIMIT
      value: "1073741824"
--
    - name: MEM_GUARANTEE
      value: "536870912"
--
        memory: "1073741824"
      requests:
--
        memory: "536870912"
    securityContext:
--
    volumeMounts:
    - mountPath: /home/jovyan
```

**Comment by felder** [comment]
`kubectl get pods --namespace=datahub-prod -o custom-columns=NAME:.metadata.name,MEM:.spec.containers[].resources.limits.memory | grep -v placeholder | grep jupyter | grep -v 1073741824`
