### ISSUE TITLE
Stat 20 DataHub

### ISSUE THREAD

**Issue by lucasadam7** [berkeley-dsep-infra/datahub#2095]
I don't seem to be allowed to install the package tidyverse in my R in the cloud session using install_packages("tidyverse"). Can you help me with this issue?

**Comment by yuvipanda** [comment]
Hello @lucasadam7. tidyverse should already be installed. Can you tell us the URL of the hub you are using. If there is a separate stat20 hub, i don't think we maintain this

**Comment by lucasadam7** [comment]
Hi, thanks for your response. The url is https://r.datahub.berkeley.edu/user/alucas/rstudio/ <https://r.datahub.berkeley.edu/user/alucas/rstudio/>

Tidyverse isn’t on the list of installed packages and I get an error when I try and install it.

thank you,
Adam

**Comment by yuvipanda** [comment]
@lucasadam7 ah, looks like there was an `.RData` file from an earlier session that was interfering with fresh loading of packages. I've moved it to `.RData.bak` (in case it is needed), and I can now access `tidyverse` properly. LMK if that works for you too!

**Comment by yuvipanda** [comment]
Me and @ryanlovett helped sort the issue of R packages not being installable. I hope the `.RData` move fixed the issue for you! Please re-open if needed.
