### ISSUE TITLE
Managing conda environments on the Datahub

### ISSUE THREAD

**Issue by bwhite-unc** [berkeley-dsep-infra/datahub#2106]
I am instructor for a CivEng203N, Graduate Hydrology and am planning to use the datahub. I'm wondering about best practices for creating conda environments. Ideally I would like to create my own environment.yml file for the class. We will be using primarily geoscience packages like xarray, Dask and rasterio. Thanks!

**Comment by yuvipanda** [comment]
Hello @bwhite-unc! Currently, we don't support multiple conda environments in a single image. The 'default' image in datahub.berkeley.edu is built from https://github.com/berkeley-dsep-infra/datahub/tree/staging/deployments/datahub/images/default. I think datashub.berkeley.edu should already have xarray, dask and rasterio. If not, I"d love for a PR to add them - that'll make it easier to get this deployed :)

**Comment by bwhite-unc** [comment]
Thanks Yuvi!  You're right that datahub.berkeley.edu has xarray/dask/rasterio. I did have trouble getting Dask-distributed to work. There are also often other minor packages and dependencies for which the flexibility to add would be helpful. A second issue I have run into wrt Dask is the memory limitation on the base image, which causes several notebooks to crash. I will open an additional comment related to this and will close this one. Thank you for the quick response!
