### ISSUE TITLE
Setup D-Lab customized datahub

### ISSUE THREAD

**Issue by aculich** [berkeley-dsep-infra/datahub#2108]
**Use cases**

1. Primarily for workshops taken by graduate students, but also faculty and undergrads and others. D-Lab Workshops: https://dlab.berkeley.edu/training

2. Research project use cases will also use this along with per-user resource customizations and shared writeable user-spaces and shared (read-only) dataset spaces.

**Any additional information we should know about?**

Start with a 'stock' datahub, can customize it more heavily later. Cost can be rolled into CDSS for now, as D-Lab is aligning/integrating more, so it's ok.

Deadline: 28th Thursday

Where: DataHub main cluster

Expected usage: Max ~200 simultaneous

Domain: dlab.datahub.berkeley.edu

Auth: Bcourses

Image: Base datahub image, might have customizations later

Resources: Start with 2G limits. Can have per-user limits later.

Future: BinderHub-likeness

TODO: 

- [x] Add bcourses callback URLs for https://dlab.datahub.berkeley.edu & https://dlab-staging.datahub.berkeley.edu
- [x] Setup hub at https://dlab.datahub.berkeley.edu
- [x] Setup DNS entries

**Comment by aculich** [comment]
@yuvipanda I'm definitely interested in the postgres sidecar for the D-Lab setup: https://github.com/berkeley-dsep-infra/datahub/pull/2124

**Comment by felder** [comment]
dlab.datahub.berkeley.edu is ready for customization, 2G limits specified, datahub base image in use.

**Comment by aculich** [comment]
I can log into staging fine, but I get this error logging into production:

![image](https://user-images.githubusercontent.com/118965/106928221-cf74de80-66c7-11eb-9163-360a34c539cd.png)

**Comment by aculich** [comment]
Now that #2162 fixes the prod issue, what are the next steps for customizing or, rather, to enable me to do self-service customization as much as possible so I don't have to bug you for things? Are there docs I should read to get started? Or are those needing to still be written (in which case I can help with that)?

In rough priority order, here's what I'd like to be able to do:
- [ ] customize the base image myself
- [ ] build from one of the "kitchen sink" images that other groups are already using with datahub that have a lot of bells and whistles already configured
- [ ] per-user configurable resource limits (e.g. to help support small group research projects that need more than the default config)
- [ ] read-only NFS shares for dataset sharing to multiple users
- [ ] group-writeable NFS shares for specific subsets of users (so they can share files and results)
- [ ] postgres sidecar mentioned in #2124

Should I open up a separate issue or continue using this one?

**Comment by yuvipanda** [comment]
Thanks for fixing this, @felder!

@aculich let's open separate issues for individual things, so we can track & close them easier?

**Comment by yuvipanda** [comment]
Closing for now. @aculich open up individual issues with customizations you want and we can work it out?
