### ISSUE TITLE
New datahub for graduate hydrology course (CivEng 203N)

### ISSUE THREAD

**Issue by bwhite-unc** [berkeley-dsep-infra/datahub#2114]
I am a faculty member teaching a CivEng graduate hydrology course with 12 students this semester and I am wondering if it would be possible for me to create a customized datahub environment for my students. I would like to be able to use Dask with higher memory allocation (to ~100GB) and scaling to ~20-50 dask workers. GPU availability would be ideal if available. I have tried the standard datahub deployment but many of my workflows (Jupyter notebooks that use Dask to load geospatial datasets) are crashing due to the 1GB memory limit and I would like to be able to have the flexibility to customize the conda environment. 

In looking at the docs.datahub.berkeley.edu it seemed like there might be a way to create customized hubs and I would be happy to do the work of creating the Jupyterhub by following the TLJH guide. Thanks!

**Comment by yuvipanda** [comment]
Per conversation elsewhere, we're going to just give students 6-8G of RAM for now, and try work with dask later.

@bwhite-unc do you have a link to your class in classes.berkeley.edu? That's what we usually use to grant particular set of students more resources.
