### ISSUE TITLE
New hub for cs194

### ISSUE THREAD

**Issue by yuvipanda** [berkeley-dsep-infra/datahub#2116]
The [data engineering class](https://www2.eecs.berkeley.edu/Courses/CS194_4349/) by Joe Hellerstein and Aditya Parameswaran requires a postgres database per user that's persistent. We did the postgres stuff for data100 last time, but it isn't persistent.

So we'll:

- [x] Add OAuth callback entries to bcourses for two hubs: https://cs194-staging.datahub.berkeley.edu and https://cs194.datahub.berkeley.edu
- [x] Create a new hub (cs194.datahub.berkeley.edu)
- [x] Copy the postgres sidecar config to it from data100
- [x] Give each user a 1GB persistent disk
- [x] Put the database on this disk
- [ ] Allow access *only* to users enrolled in the class

**Comment by felder** [comment]
@yuvipanda Added the callback entries to bcourses.
