### ISSUE TITLE
Request for ESPM-288 allocation

### ISSUE THREAD

**Issue by cboettig** [berkeley-dsep-infra/datahub#2137]
**Which package do you want installed?**

`rjags`, (which will probably `jags` libs installed via apt-get).  

Also, we need student accounts to have at least 8 GB RAM and at least 30 GB disk space.  (We don't have many students this year though so hopefully not too big a footprint?)

**Which hub do you want it installed on?  For example r.datahub, datahub, data100.datahub, etc.**

r.datahub

**Which class will use this package?**

ESPM-288, Carl Boettiger, https://classes.berkeley.edu/content/2020-spring-espm-288-001-lab-001

**Which semester will this package be used for?**

Spring 2021

**Any additional information we should know about?**

**Comment by yuvipanda** [comment]
@cboettig rjags was installed yesterday - apologies for not mentioning it here.

Can you tell us how many students your class has? We try to not go over 4G a student if possible, but if that's what your class needs we can find a way to make it work.

**Comment by cboettig** [comment]
~ 12 students

**Comment by cboettig** [comment]
we could try and squeeze into 4 (maybe 6) GB for now and let you know how it goes?

**Comment by yuvipanda** [comment]
@cboettig can you try it now? I gave you 8G, since it isn't that many users
