### ISSUE TITLE
Investigate and migrate repo secrets migration from git-crypt to sops.

### ISSUE THREAD

**Issue by felder** [berkeley-dsep-infra/datahub#2229]
Sops:
http://github.com/mozilla/sops/

**Comment by yuvipanda** [comment]
Also see https://github.com/berkeley-dsep-infra/datahub/issues/596

**Comment by felder** [comment]
Installed latest stable version of sops on my workstation with homebrew.

**Comment by felder** [comment]
Was able to checkout, view, and edit the test in #596 after authenticating with google:

gcloud config set project data8x-scratch
git clone https://github.com/yuvipanda/sops-key-test
sops --gcp-kms 'projects/data8x-scratch/locations/global/keyRings/data8x-sops-test' test.yaml

**Comment by felder** [comment]
The big differences between sops and git-crypt is that we'll probably want to have sops authenticate using a gcp service account to grab the key from gcp-kms and sops will need to be executed against each secrets file to decrypt it as part of the image build/deployment process.

**Comment by yuvipanda** [comment]
hubploy alread supports [decrypting sops encrypted files](https://github.com/yuvipanda/hubploy/blob/master/hubploy/auth.py#L365). So if we have a service account activated that can access the appropriate key in KMS, hubploy should 'just work' in decrypting/reading the sops encrypted file.

Here's a sample on [how to activate a gcp service account for use with sops](https://github.com/utoronto-2i2c/jupyterhub-deploy/blob/staging/.github/workflows/deploy.yaml#L15). It's using GitHub actions, but should translate fairly easily to CircleCI.

**Comment by felder** [comment]
https://circleci.com/docs/2.0/google-auth/

**Comment by felder** [comment]
@yuvipanda so theoretically I should be able to:

1.  Create a new gcp service account with access to KMS
2. Use the instructions in my above comment to activate it during the build-image job
3. Add a sops encrypted yaml file for one of the deployments
4. hubploy should do the rest?

Also how do I do this without causing a huge disruption in the existing deployments?  For one, I'm going to need to have the config not be git-crypted, but that's probably not ideal for testing.

**Comment by yuvipanda** [comment]
@felder so hubploy supports both git-crypt and sops transparently (see https://github.com/yuvipanda/hubploy/blob/6c1752dbb925711df3e1d3f0b291a7458767b8fc/hubploy/auth.py#L365). If a file looks like it's sops encrypted, it'll try to decrypt it first. Else it'll go with the default (git-crypt). 

So you can just change one file and test it out. Otherwise your plan looks solid.

**Comment by felder** [comment]
After some help from @yuvipanda this morning just to make sure I didn't do something stupid, I've now converted all of the secrets in staging.yaml for each hub to sops.

Note that currently template/{{cookiecutter.hub_name}}/secrets/staging.yaml is also encrypted.

I wasn't sure if moving that over to sops would break cookiecutter.  I suspect it might since git-crypt decrypts everything when you checkout the repo whereas sops does not.

The file contains no actual secrets so I could probably just ignore it.  We should consider the workflow though or perhaps see if cookiecutter can invoke sops to produce an encrypted file when the template is utilized.

**Comment by felder** [comment]
This has been live in prod for a few days.  Closing.
