### ISSUE TITLE
Request R packages rJava and several others for D-Lab workshops

### ISSUE THREAD

**Issue by aculich** [berkeley-dsep-infra/datahub#2230]
**Which package do you want installed?**

The following are all R packages: `data.table, tidyr, dplyr, car, dummies, MASS, rsq, bartMachine, googledrive, stringr, totalcensus, fastDummies, factoextra, FactoMineR, mpath, BMA, ggplot2, rmapshaper, scales, plotly, spdep, tidyverse, tidycensus, tigris, tmap, leaflet, devtools, rJava`

**Which hub do you want it installed on?  For example r.datahub, datahub, data100.datahub, etc.**

dlab.datahub.berkeley.edu

**Which class will use this package?**

Several D-Lab workshops listed here: https://dlab.berkeley.edu/training

**Which semester will this package be used for?**

During Spring, Summer, and Fall terms.

**Any additional information we should know about?**

After this, if it is easier for me to submit a PR then I can do that rather than submit an issue.

**Comment by yuvipanda** [comment]
@aculich Awesome! 

1. Can you check which of these packages are already installed? `installed.packages()` in an R session should tell you. I think most of these already are!
2. Can you make a PR to https://github.com/berkeley-dsep-infra/datahub/tree/staging/deployments/datahub/images/default? I think you should create a file under `r-packages`, and then invoke it from Dockerfile like the others.
