### ISSUE TITLE
Request R package pegas for class IB161

### ISSUE THREAD

**Issue by aguilar-gomez** [berkeley-dsep-infra/datahub#2243]
**Which package do you want installed?**
pegas

**Which hub do you want it installed on?  For example r.datahub, datahub, data100.datahub, etc.**
r.datahub
**Which class will use this package?**
IB 161 with Rasmus Nielsen https://classes.berkeley.edu/content/2021-spring-integbi-161-001-lec-001

**Which semester will this package be used for?**
Spring 2021
This helps us clean up unused packages after a term ends.

**Any additional information we should know about?**

**Comment by yuvipanda** [comment]
Hi @aguilar-gomez! I can't seem to find an R package named `pages`. [This page](https://packagemanager.rstudio.com/client/#/repos/1/packages) lists all of CRAN and is where we prefer to install R packages from. I also couldn't really find it on the web. Do you know where it is?

**Comment by aguilar-gomez** [comment]
It is called “pegas” not “pages”. With the vowels flipped. I installed it very easily for myself with install.packages(“pegas”). 

Thank you,
Diana
