### ISSUE TITLE
Links_to_Datahub_No_Longer_Work_Error_Message_Included

### ISSUE THREAD

**Issue by sungsy12345** [berkeley-dsep-infra/datahub#2269]
Dear Whom It May Concern,

I erased one of the Jupyter Notebook files in my Datahub class folders, hoping I would get back an original version of the Jupyter Notebook file I had erased by re-clicking on the nbgitpuller-produced link provided to class for accessing this file. While re-pressing on the nbgitpuller-produced link did get the original version of the file added back to my Datahub folders, the links provided to students that used to take me directly to specific ipynb files no longer works and gives me the following message. 

<img width="876" alt="Error_Message" src="https://user-images.githubusercontent.com/40625821/111894575-1e04e080-89c9-11eb-9595-a43e9714e8ba.png">

If you look at the last line of code, it includes the "Lectures5.ipynb". This is actually the file that I deleted, not in github, but in Datahub in order get back an original version of it. And, I do have the original version back, but it still gives me this error message for any nbgitpuller-produced links I use. (FYI, I am one of the GSIs for this class.)

I would appreciate guidance on resolving this issue.

Thank you,

**Comment by felder** [comment]
Can you provide me with steps to replicate this behavior as well as your calnet username?

**Comment by sungsy12345** [comment]
Thanks for your response. My calnet id is "sysung".

(1) In my datahub, I have the "/ENVECON-118/Spring2021-J/Lectures/" folder. In the datahub, I erased all the files (ipynb, csv, and readme.md files) in this folder and its sub-folders, because I wanted original files to be reloaded.

(2) Again, I was hoping to get original files back. Hence, I clicked on the following button, which we provided the students, that takes them directly to one of the ipynb files in the folder I deleted: 

https://r.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=http%3A%2F%2Fgithub.com%2Fds-modules%2FENVECON-118&urlpath=tree%2FENVECON-118%2FSpring2021-J%2FLectures%2FLecture5%2FLecture5.ipynb&branch=master

Then, above message started showing up. It initially would not resync and load the original files of which I deleted. But after a while, I did get the original files back.

Unfortunately, when I click on other links that takes students to other ipynb files, I get the same error message, despite clicking on the link correctly syncing the datahub folders to load new files added to github.

**Comment by felder** [comment]
@sungsy12345 I was able to reproduce this issue via your server.

When I open a terminal from your server and run "git status" this is what I see:

```
jovyan@jupyter-sysung:~/ENVECON-118$ git status
On branch master
Your branch is ahead of 'origin/master' by 54 commits.
  (use "git push" to publish your local commits)

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        deleted:    Spring2021-J/Lectures/Lecture5.ipynb
        deleted:    Spring2021-J/Lectures/Lecture5_Spring2021run.ipynb
        deleted:    Spring2021-J/Lectures/Readme.md
        deleted:    Spring2021-J/Problem-Sets/ProblemSet3/ProblemSet3_2021.ipynb
        modified:   Spring2021-J/Problem-Sets/ProblemSet4/ProblemSet4_2021.ipynb
        modified:   Summer-19/ProblemSet5/PS5_Template.ipynb

```
Also note I can also reproduce this by running the commands indicated in your error message:

```
jovyan@jupyter-sysung:~/ENVECON-118$ git fetch
jovyan@jupyter-sysung:~/ENVECON-118$ git checkout origin/master -- Spring2021-J/Lectures/Lecture5.ipynb
error: pathspec 'Spring2021-J/Lectures/Lecture5.ipynb' did not match any file(s) known to git
jovyan@jupyter-sysung:~/ENVECON-118$ 

```
Additionally, when I look at the directory in question this is what I see:

```
jovyan@jupyter-sysung:~/ENVECON-118$ ls -l Spring2021-J/Lectures/
total 4
drwxr-xr-x 3 jovyan jovyan 111 Mar 20 21:42 Lecture5
-rw-r--r-- 1 jovyan jovyan  16 Mar 20 21:42 readme.md
jovyan@jupyter-sysung:~/ENVECON-118$ 

```
Note that the complaint is the missing file.

I believe that git status also provides the remedy.  You need to run:
`git restore Spring2021-J/Lectures/Lecture5.ipynb`

```
jovyan@jupyter-sysung:~/ENVECON-118$ git restore Spring2021-J/Lectures/Lecture5.ipynb
jovyan@jupyter-sysung:~/ENVECON-118$ ls -l Spring2021-J/Lectures
total 12
drwxr-xr-x 3 jovyan jovyan  111 Mar 20 21:42 Lecture5
-rw-r--r-- 1 jovyan jovyan 6144 Mar 23 10:16 Lecture5.ipynb
-rw-r--r-- 1 jovyan jovyan   16 Mar 20 21:42 readme.md
jovyan@jupyter-sysung:~/ENVECON-118$ 

```

Doing that allows to nbgitpuller process to continue, but it fails on the next missing file.

```
$ git fetch
$ git checkout origin/master -- Spring2021-J/Lectures/Lecture5_Spring2021run.ipynb
error: pathspec 'Spring2021-J/Lectures/Lecture5_Spring2021run.ipynb' did not match any file(s) known to git
Traceback (most recent call last):
File "/opt/conda/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
File "/opt/conda/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
File "/opt/conda/lib/python3.8/site-packages/nbgitpuller/handlers.py", line 88, in pull
    raise e
File "/opt/conda/lib/python3.8/site-packages/nbgitpuller/handlers.py", line 82, in pull
    for line in gp.pull():
File "/opt/conda/lib/python3.8/site-packages/nbgitpuller/pull.py", line 86, in pull
    yield from self.update()
File "/opt/conda/lib/python3.8/site-packages/nbgitpuller/pull.py", line 203, in update
    yield from self.reset_deleted_files()
File "/opt/conda/lib/python3.8/site-packages/nbgitpuller/pull.py", line 115, in reset_deleted_files
    yield from execute_cmd(['git', 'checkout', 'origin/{}'.format(self.branch_name), '--', filename], cwd=self.repo_dir)
File "/opt/conda/lib/python3.8/site-packages/nbgitpuller/pull.py", line 45, in execute_cmd
    raise subprocess.CalledProcessError(ret, cmd)
subprocess.CalledProcessError: Command '['git', 'checkout', 'origin/master', '--', 'Spring2021-J/Lectures/Lecture5_Spring2021run.ipynb']' returned non-zero exit status 1.
```

The nbgitpuller link now works after first running git restore on each missing file:

```
jovyan@jupyter-sysung:~/ENVECON-118$ git restore Spring2021-J/Lectures/Lecture5_Spring2021run.ipynb
jovyan@jupyter-sysung:~/ENVECON-118$ git restore Spring2021-J/Lectures/Readme.md
jovyan@jupyter-sysung:~/ENVECON-118$ git restore Spring2021-J/Problem-Sets/ProblemSet3/ProblemSet3_2021.ipynb
```

**Comment by felder** [comment]
@sungsy12345 please let me know if this resolves your issue.

**Comment by sungsy12345** [comment]
@felder  Thank you so much. The issue seems to be remedied perfectly! I really appreciate your time and insight.

**Comment by felder** [comment]
Great!
