### ISSUE TITLE
Grant more CPU to users in eecs hub

### ISSUE THREAD

**Issue by felder** [berkeley-dsep-infra/datahub#2322]
@Quizenger reports that students are experiencing long run times when doing their course work on the eecs hub.  A look at the graphs from yesterday does suggest high cpu utilization.

I'm going to start with CPU guarantee of .25 which I believe should place 32 students on a single node.

**Comment by felder** [comment]
@Quizenger yesterday cluster utilization peaked around 60% as opposed to 100% the day before.

Did your students also see improved performance?

**Comment by Quizenger** [comment]
@felder Yes! The runtime dropped significantly for most students. We still had a few at around 10 mins (down from 20 for most). Do you think we can increase the CPU guarantee further? (We only need this until the end of next week, 4/30)

Thanks so much for your help, appreciate it!

**Comment by felder** [comment]
@Quizenger yeah let's give .33 a shot.  That should take us from ~32 to ~24 users per node.

My only concern here is that peak utilization at a guarantee of 0.25 was 60% which may imply that additional bumps won't do much.  One thing to note is that while we're using a minimum guarantee there is no limit set.  So I'd expect lots of students with CPU bound processes to result in 100% utilization like we saw the other day.

I'll go ahead and do the increase now, but I also think @yuvipanda should maybe look at the utilization tonight and see if we're accomplishing much.  

Additionally please let me know in this ticket tomorrow how things are going.

**Comment by felder** [comment]
Unsurprisingly these changes have resulted in the spinning up of additional nodes.  I modified the autoscaling rules for the gamma node pool to permit a max of 30 nodes instead of 20.

**Comment by felder** [comment]
The gamma node pool is hovering around 18 nodes.  I'm bumping the gamma node pool's max from 30 to 40 nodes.

Just want to be sure we don't run out of nodes if there is a surge of users.

**Comment by Quizenger** [comment]
We're still facing issues with some students facing >15 min wait times.

I assume the gamma node pool is a backup pool of resources in case there are too many users?

**Comment by yuvipanda** [comment]
@Quizenger how has it been today/

**Comment by Quizenger** [comment]
It was better, thank you!

**Comment by yuvipanda** [comment]
https://github.com/berkeley-dsep-infra/datahub/pull/2365 will turn this off.

@Quizenger can you share the profiling info (both the py-spy and top one) here so we can refer back to it next semester?

**Comment by Quizenger** [comment]
![top](https://user-images.githubusercontent.com/58498249/116849123-b23ea600-ac0b-11eb-98f7-e18e707010d5.png)

**Comment by Quizenger** [comment]
![py-spy profile](https://user-images.githubusercontent.com/58498249/116849228-ffbb1300-ac0b-11eb-9069-3715457646ca.png)

**Comment by yuvipanda** [comment]
To summarize these graphs:

1. The assignment seems to use 2 CPUs, not 1. So it was pretty slow for many students even with a 1 CPU guarantee, because we also had a 1 CPU limit (the output of `top`)
2. The code is spending almost all its time in numpy code, so while that could be optimized, it is in fact CPU bound

**Comment by balajialg** [comment]
@Quizenger Let's communicate over here and figure out a solution asap! Sharing the context shared over email for the team,

> I've set this thread up to discuss the EECS 16A  APS Lab performance issues on Datahub.
>
> The APS labs use Jupyter Notebooks and basically have a few sound recordings (.wav files) on which we perform signal processing. Essentially, some large vectors and linear algebra. Length of the sound recording is 511000 samples.
> I met with Linda this afternoon and we compared local lab PC v. Datahub performance. Code blocks that take ~15 seconds locally took ~3 mins on Datahub. And this is with probably me being the only user node in the pool. When there are ~70 students running the lab simultaneously, the same code blocks take anywhere between 5-15 mins. Yuvi and I have tried to analyze the performance issues over the last few semesters. (Yuvi, please pitch in with your description and analysis of our issues.) We could really use help from the department in solving this, particularly regarding increased funding for more compute resources.
>
> I look forward to hearing from y'all! We need to have these issues sorted by the end of October as the labs must be deployed soon after.

**Comment by raghav-g13** [comment]
Can we increase CPU guarantee and limit temporarily? (we've brought down our requirements of simultaneous users from ~70 to ~20 so I hope this is possible?)

**Comment by felder** [comment]
So the continuous integration server is really giving me the once over today.

What I've done is modified the eecs config locally to provide a guarantee of 0.33 CPU with a limit of 2 and pushed it directly.  I believe that's what we did the last time.

However, that change is not going to stick if another deployment is performed later.

@yuvipanda pinging you here to let you know the situation.  I also bumped up the max size of the beta pool just in case this causes a bunch of nodes to spawn.

**Comment by balajialg** [comment]
Thank you so much @felder for quickly looking into this issue and figuring out a solution! Since you deployed via hubploy, there won't be any relevant PR mapped to it?

**Comment by felder** [comment]
@balajialg that's correct.

**Comment by balajialg** [comment]
@Quizenger Let us know if you still face any issues with hub performance!

**Comment by balajialg** [comment]
@felder Should we close this issue assuming nothing was reported in the past two days?

**Comment by felder** [comment]
@balajialg yeah it's probably safe to close this.  If eecs reports more issues we can reopen it.

**Comment by raghav-g13** [comment]
Looks good so far, TAs reported improvements on Friday. Thank you so much everyone for your support!

**Comment by felder** [comment]
Just to add a quick note.  @Quizenger says that eecs 16a requires these allocations until December 10.
