### ISSUE TITLE
Request more RAM for Data Arts

### ISSUE THREAD

**Issue by gregottoniemeyer** [berkeley-dsep-infra/datahub#2330]
**Which hub do you want more RAM on?**

Datahub

**Which class is this request for?**

https://classes.berkeley.edu/content/2021-summer-art-w23ac-101-wbl-101

**How many students do you expect in this class?**

40

**How much RAM does this class need?**

1 GB RAM for students
16 GB RAM for instructor (niemeyer@berkeley.edu)

**Why does this class need this much RAM?**

network analysis with networkx

Instructor wants to run zero shot classifiers => 16 GB ram.

**Comment by felder** [comment]
@gregottoniemeyer 16GB is a pretty large memory allocation.  Is there an end date for this, such just for the summer?

Also is this something that could be better run locally?

**Comment by felder** [comment]
Added requested RAM for the students.

**Comment by gregottoniemeyer** [comment]
Dear Berkeley-Dsep-Infra/Datahub,
First, thanks for datahub. It's one of the *best* things Berkeley has to
offer. Second, yes, only for the summer, and students need 1 GB.
I would like 16GB until further notice, so I can demo more advanced stuff.
Best wishes, Greg
Greg Niemeyer

Professor for New Media
Department of Art Practice
University of California at Berkeley
https://art.berkeley.edu

**Comment by felder** [comment]
@gregottoniemeyer Just to be clear you're saying you would prefer to have the 16GB memory allocation permanently with no current end date correct?  I want to discuss this a little bit more internally before we move forward.  I already adjusted the requested change for your class.  My concern is specifically around the 16GB you're requesting.  

I'm inclined to grant it, but the main issue here is that in general our nodes are memory limited not cpu limited.  Additionally each node has ~48GB of RAM.  So you're essentially requesting to be allocated 1/3 of node which typically serves upwards of 50-80 people at a time (you're asking for 32x the default student allocation).  Not necessarily an issue, but there's an ongoing conversation internally about resource allocations and service costs.

Stay tuned.

**Comment by felder** [comment]
@gregottoniemeyer ok, after a bit of discussion, how would you feel about a 4GB memory guarantee with an 8GB memory limit?  Then you can do some testing and we can adjust upwards if that's not sufficient.  Just in case you're not aware, you can keep an eye on memory usage in the upper right corner.  It'll turn red as you get close to your limits.

One idea for this might be to allow you to choose your allocations if you know you're going to demo something with large memory requirements, then you could choose the higher memory allocation on sign in:
https://zero-to-jupyterhub.readthedocs.io/en/latest/jupyterhub/customizing/user-environment.html#using-multiple-profiles-to-let-users-select-their-environment

I'm going to open an issue to discuss that option specifically.  This way you'd have the memory if you need it, but if you're not doing a memory intensive demo you could sign in and opt for the normal (lower) amount.

**Comment by gregottoniemeyer** [comment]
Thanks, that sounds good. One transformer I use is 1.5 GB and so with 8 GB
top I should be fine. With 1 GB it obviously crashed.
With the multiple profiles I wonder if both profiles will access the same
files?
Best wishes
=GN=

Greg Niemeyer

Professor for New Media
Department of Art Practice
University of California at Berkeley
https://art.berkeley.edu

**Comment by felder** [comment]
@gregottoniemeyer note that the multiple profile selection is not something we're prepared to offer just yet.  However, I think it may be a good solution for enabling us to allow large allocations while also keeping costs down.  Right now, when we honor a request for increased resources, those resources are always allocated when someone signs in whether they think they need them or not.  16GB of RAM is a lot to allocate if you're signing in just to assist a student with their environment or doing something else that doesn't require it.

Since you're ok with the 4GB + 8GB, we'll start there and see how it goes.

**Comment by felder** [comment]
@gregottoniemeyer ok that should do it

**Comment by gregottoniemeyer** [comment]
Dear Felder:
Thanks for your help. I have another question: How can I access and update
the Art 23 AC folder that students have access to? The examples need to be
revised.
Thanks, Greg
Greg Niemeyer

Professor for New Media
Department of Art Practice
University of California at Berkeley
https://art.berkeley.edu

**Comment by felder** [comment]
@gregottoniemeyer Do you mean from your git repo?  If so, these instructions should help you with constructing nbgitpuller links to distribute to your students:

https://jupyterhub.github.io/nbgitpuller/

**Comment by gregottoniemeyer** [comment]
Ah thanks! I did not realize git was the way!

**Comment by gregottoniemeyer** [comment]
Dear Felder,
I understand what you mean... I think someone else wrote these lessons for
a previous version of my course. So the issue is how can I edit what repo
the students are getting. Someone automatically gave all students access to
the old version. The easiest would be for me to edit that repo and update
it, but I am not sure that I have access.
Thanks, Greg

Greg Niemeyer

Professor for New Media
Department of Art Practice
University of California at Berkeley
https://art.berkeley.edu

**Comment by felder** [comment]
@gregottoniemeyer I think you'll probably either want to fork the old repo or clone it into a completely new project.

Below is instructions for doing both:
https://guides.github.com/activities/forking/
https://stackoverflow.com/questions/9844082/how-to-create-a-new-git-repository-from-an-existing-one

Additionally, you may want to reach out to @ericvd-ucb.  In the before times (pre covid) he gave short tutorials every semester or so that talked about how to best organize student materials for use in the hub.  He might be able to give you some advice on how best to proceed.  You could also discuss your use case with him in greater detail as he's very knowledgeable (more knowledgeable than me) about using the hub for pedagogy.

**Comment by gregottoniemeyer** [comment]
Thanks Felder, and Hi Eric:
Trouble is I have no idea where the old repo is.
I will follow up with Eric who I believe was involved in creating the
original repo.
Thanks for your help and patience,
Greg
Greg Niemeyer

Professor for New Media
Department of Art Practice
University of California at Berkeley
https://art.berkeley.edu

**Comment by ericvd-ucb** [comment]
@gregottoniemeyer 
https://github.com/ds-modules/ART-W23AC

**Comment by felder** [comment]
I don't believe there's any more work to do here.  Please reopen and let me know if there is.
