### ISSUE TITLE
Fall 2021 big tasks planning

### ISSUE THREAD

**Issue by yuvipanda** [berkeley-dsep-infra/datahub#2333]
This issue tracks tasks we want to get done before Fall 2021.

1. Removing undergrad admins from main datahub #1965 
2. Implement data archival policy for home directories #1633 

(1) has a few primary sub tasks.

- [x] Make it easy to provide one hub per class (https://github.com/berkeley-dsep-infra/datahub/pull/2115)
- [x] Move data8 to its own hub - most undergrad admins are for data8 (https://github.com/berkeley-dsep-infra/datahub/issues/2334)
- [x] #2671
- [ ] #2669
- [x] Fix the culler #2452

**Comment by felder** [comment]
One nice to have for Fall would be a clear support path for students (or their professors) to get assistance.

I envision such a thing occurring via service now through the campus help desk.  The service now ticketing system would provide the privacy required for avoiding FERPA issues as well as make easier to engage other campus IT departments as necessary (for example CalNet).

It's a bit of a tall order, but I can discuss this internally with other service managers at RTL who have transitioned support triaging to the service desk for their services.

**Comment by yuvipanda** [comment]
Totally agree, @felder. I'd imagined this would be most important first task for new data science lead.

**Comment by felder** [comment]
@yuvipanda the reason I mention servicenow specifically is it that's what central campus IT as a whole uses for ticketing.  Thus it makes it easy to hand off tickets to different groups as necessary.  It also shifts security concerns in tickets from us to service now. :)

**Comment by felder** [comment]
So another issue for fall is clarity around requests for resource grants and how we handle them.  I'm thinking specifically of unusual requests such as #2330

What's our policy regarding requests for additional resources?  Which requests do we allow or refuse?  
 
Additionally, I think consulting with regard to resource allocations might be something we need to offer.  I feel when requests for additional resources are made we need to know/monitor if those resources are being used efficiently. However, I admit that's a pretty difficult task in general.

**Comment by felder** [comment]
@yuvipanda adding #2452 to the list, pretty sure we don't to start the fall semester with the idle culler not working.

**Comment by balajialg** [comment]
@yuvipanda Has any thought been given w.r.t parameters used to evaluate whether a course gets a separate hub?

You mentioned in #2008 that if a course requests admins, that is a good indicator that we should consider providing a separate hub to them. Should we also think about coupling that with parameters around class size, usage scope, financial support, etc., to narrow that decision?

**Comment by balajialg** [comment]
@yuvipanda Moved this issue to October Sprint! Let me know if that is okay for you.

**Comment by yuvipanda** [comment]
@balajialg let's keep this out of the sprint boards - #2669 and #2670 can be in sprints, and we can close this when that's done. What do you think about that?

**Comment by yuvipanda** [comment]
#2669 is what is left, so I'm going to close this issue for now.

**Comment by balajialg** [comment]
Sounds good!
