### ISSUE TITLE
Make a new hub specifically for data8

### ISSUE THREAD

**Issue by yuvipanda** [berkeley-dsep-infra/datahub#2334]
We're trying to remove admin permissions from all undergrads on datahub (https://github.com/berkeley-dsep-infra/datahub/issues/1965). data8 has the largest share of admins there, so moving it to its own hub will let us remove all of them from datahub.

**Comment by ericvd-ucb** [comment]
Hey there - update from soft side   - I got approval from Fall Profs for this - and from Summer instructor @Yanay1  - could you update when this might come online?

**Comment by yuvipanda** [comment]
I'm hoping to have this done by Monday :)
