### ISSUE TITLE
sops is duplicating comments in secrets files

### ISSUE THREAD

**Issue by felder** [berkeley-dsep-infra/datahub#2395]
@ryanlovett noticed several duplicate comments in the secrets files.  The culprit appears to be sops.  I was able to devise a trivial test case that reproduces the bug and I filed a bug report with the sops project:

https://github.com/mozilla/sops/issues/865

Note that I also linked this issue another issue that mentions sops also reformatting comments:

https://github.com/mozilla/sops/issues/864

It doesn't seem like the sops devs plan on fixing that issue, but I think the duplicate comment issue is more severe.  So hopefully they'll address it.

**Comment by felder** [comment]
In theory this has been fixed:
https://github.com/mozilla/sops/pull/866

Hopefully this fix will make into the next release.

**Comment by balajialg** [comment]
@felder Is this issue still relevant?

**Comment by felder** [comment]
@balajialg yes it is.

I'm waiting for the next official release where I presume this bug will be patched.

**Comment by felder** [comment]
Latest release of sops in theory should fix this.  I'm testing it now.

https://github.com/mozilla/sops/releases/tag/v3.7.2

**Comment by felder** [comment]
Sops 3.7.2 installed via homebrew works!

```
$ sops --version
sops 3.7.2 (latest)
$ cat test.yaml
a:
    b:
        c:
            - name: test_1
              test: a
            # I get duplicated
            - name: test_2
              test: b
$ sops -e --verbose -i test.yaml
[GCPKMS]	 INFO[0000] Encryption succeeded                          
[CMD]	 INFO[0000] File written successfully
$ sops -d test.yaml
a:
    b:
        c:
            - name: test_1
              test: a
            # I get duplicated
            - name: test_2
              test: b
```
