### ISSUE TITLE
Line magic function errors

### ISSUE THREAD

**Issue by ryanlovett** [berkeley-dsep-infra/datahub#446]
A gsi reported to me:
> Sorry to bother you so much, but ... one of the professors for Data 8 for Spring '19 was running through the old homeworks on Fall 2018, and noticed that an error was being thrown when using line magic functions (e.g. % matplotlib inline), with the error being that the line magic function is not found. I also tried it and ran into the same error.
> 
> Do you know why this could be the case? It was working during the semester (Fall '18), and the iPython version that we're running on the hub is 7.2.0 which should have support for it.

**Comment by yuvipanda** [comment]
would be useful to have the actual error message. Maybe matplotlib isn't installed? 

Also there's no space between '%' and 'matplotlib'. Maybe that?

**Comment by ryanlovett** [comment]
I tracked down the notebook in the gsi's account, hw01.ipynb.
![screen shot 2019-01-17 at 12 46 07 pm](https://user-images.githubusercontent.com/10248125/51347605-717bec80-1a55-11e9-8127-07d0b4cf24a1.png)

**Comment by ryanlovett** [comment]
@nirajrao confirmed that removing the space after the magic token works.
