### ISSUE TITLE
Make PDFs work

### ISSUE THREAD

**Issue by yuvipanda** [berkeley-dsep-infra/datahub#47]
This requires pandoc and probably the xelatex pages.

@ryanlovett can you take a look when you have time? I don't know what the required timeline for this is but @gunjanbaid / @henchc / @vinitra would!

**Comment by ryanlovett** [comment]
Yes, will look this evening. In the past it did require xelatex on account of utf things perplexing pdflatex. Adding the necessary packages will increase the image size a moderate amount.

**Comment by gunjanbaid** [comment]
Connector courses did not meet last week, they will all have the first meeting this Monday and Tuesday. So assignments will probably not be due until middle or end of this upcoming week, I would think.

**Comment by ryanlovett** [comment]
Should be fixed by #48.

**Comment by ryanlovett** [comment]
Pushed to prod as #53.
