### ISSUE TITLE
Try set up a different image / hub for R

### ISSUE THREAD

**Issue by yuvipanda** [berkeley-dsep-infra/datahub#479]
@ryanlovett do you know which courses use R on datahub? I wanna try making a different image for them and build the stuff necessary to make that be deployed smoothly...

**Comment by ryanlovett** [comment]
ericvd (@?) keeps closer tabs on that than I. He recently requested R library additions for Econ 172. I'll start an email thread and/or try to ping him here.

**Comment by yuvipanda** [comment]
This isn't a super high priority right now. If we do do this, we must do this in a way that causes 0 disruption to the people using R, and making it clear they are first class citizens here.

**Comment by ericvd-ucb** [comment]
Hey there - Right now as I know it it is Econ 172 and and Info class that I don't know the number taught by Alex Hughes

**Comment by ericvd-ucb** [comment]
Thanks for thinking about Rstudio users!

**Comment by d-alex-hughes** [comment]
Yes, thanks for thinking about the Rstudio users! I've got 60 students who are working in Rstudio on a weekly basis currently.

**Comment by yuvipanda** [comment]
@d-alex-hughes @ericvd-ucb awesome :) We won't change anything this semester. We want RStudio on DataHub to be a first class citizen, so let us know how we can make that be :)

**Comment by d-alex-hughes** [comment]
I really appreciate that commitment, @yuvipanda and @ryanlovett @ericvd-ucb . The experience on the data hub has been _really_ positive to this point. Students' code this semester is notably better this semester than last, an improvement that I think could only be attributed to their in-location practice with code vs. concepts. Thanks!

**Comment by yuvipanda** [comment]
@d-alex-hughes we now have https://r.datahub.berkeley.edu which is a dedicated hub for R that launches users directly into R Studio :) Give it a shot?

**Comment by yuvipanda** [comment]
Going to close this now that r.datahub.berkeley.edu exists.
