### ISSUE TITLE
Extra Memory for LS 88

### ISSUE THREAD

**Issue by ericvd-ucb** [berkeley-dsep-infra/datahub#505]
@ryanlovett ok here is a new issue - I was trying to get in the PR instead of em flow here - but github recommended other open issues.....

Sarah Reynolds  LS88 Children in the Developing World needs some extra memory. She says that @TomPiona had taken care of it in the past. I asked her for her class roster for whitelisting.  Not urgent.

**Comment by ryanlovett** [comment]
Thanks! Is this LS 88 1? I think I can pull the roster myself.

**Comment by ericvd-ucb** [comment]
https://classes.berkeley.edu/content/2019-spring-ls-88-001-sem-001

CCN #26918

**Comment by ryanlovett** [comment]
Got the list, thanks @ericvd-ucb. How about we double the memory then Sarah can test it with her notebooks?

**Comment by yuvipanda** [comment]
Was this done? can we close this?
