### ISSUE TITLE
Extra memory for Astr 128 and 256

### ISSUE THREAD

**Issue by kareemelbadry** [berkeley-dsep-infra/datahub#508]
Running our labs on datahub, I noticed that some of them run out of memory with the 1 GB limit. Obviously some of problems can be avoided by writing more memory-efficient code, but a bit more flexibility would be nice if possible. 

Could we get, say, 4 GB? If it makes a difference, the class has 23 students.

**Comment by yuvipanda** [comment]
@kareemelbadry the way we try to do this is:

1. Give the GSI / Admins access to 4G of RAM
2. Have them measure how much RAM students are actually using (there's a memory status bar on top right)
3. Give that much RAM to students.

If there's an emergency, we can reverse this - give 'em RAM first and measure afterwards. But we often find that sometimes when students use more than 1G of RAM, they often end up accidentally trying to use 100s of Gs of RAM - infinite recursion, etc. This helps tune that.

**Comment by yuvipanda** [comment]
Unfortunately it still requires one of us (me or @ryanlovett) to do it. Can you gimme your calnet id and I'll get it set up.

**Comment by ryanlovett** [comment]
@yuvipanda I've made a PR, #511. One tip: if you know or can guess at a person's name, you can type it into a gmail compose window and Google will autocomplete it. It isn't always unambiguous though.

**Comment by ryanlovett** [comment]
@kareemelbadry Thanks for your patience, your account now has a 4g limit on prod. You'll need to restart your server if it was running when the change was deployed.

**Comment by kareemelbadry** [comment]
OK, I've now tested all the labs. They all run with 4 GB, but one of them used almost all available RAM, (3.9 GB, without any parallelization). Given this, would it be possible to give all the students 4 GB?

**Comment by ryanlovett** [comment]
@kareemelbadry All your students should have the increased limit now. They'll need to restart any existing server.

**Comment by kareemelbadry** [comment]
One of the students in the graduate listing of this course (Astr 256) reported never having gotten extra memory. There are only a couple people in the grad version, so it's possible that the grads never got extra memory. 

Sorry for the change late in the semester, but can we bring Astr 256 to 4 GB as well?

**Comment by ryanlovett** [comment]
Hi @kareemelbadry, this should be fixed when https://github.com/berkeley-dsep-infra/datahub/pull/624 lands in prod.

**Comment by ryanlovett** [comment]
Done.
