### ISSUE TITLE
Gain JupyterHub admin access for data 8X hub

### ISSUE THREAD

**Issue by sideye** [berkeley-dsep-infra/datahub#518]
Would it be possible to grant the data 8X staff admin access for the data 8X hub? It will be useful to be able to more easily debug students' notebooks.

I can email the associated unique course ID's.

**Comment by yuvipanda** [comment]
@sideye yes! You can leave it here, and I'll make a PR. That'll also make it easy for you to add more people as time goes on.

Thanks!

**Comment by sideye** [comment]
Thanks!

**Comment by Yanay1** [comment]
a7b92e1bffedf669c8301f76e617f255

**Comment by yuvipanda** [comment]
@sideye can you leave a comment here with the GitHub handles (or EdX ids) of people who should be granted admin access? I don't know who all are involved - and @felder and I wanna make sure we don't hand out admin access to folks who shouldn't have it.

**Comment by sideye** [comment]
@yuvipanda absolutely! There are 4 members + me on the Data 8X staff. Their names and GitHub accounts are:
Ryan Roggenkemper @rroggenkemper
David Yi @kvah 
Yanay Rosen @Yanay1 
Sam Wu @samwu101
(Me) Alan Liang @sideye 
Thanks!

**Comment by felder** [comment]
@sideye thanks!  I'll add the 7 ids above now.

**Comment by samwu101** [comment]
Here are my 3 codes:
9cb1fbfa7af6472dc8d8dddc28b905be
e39a60f081cdfd06347d83df61af4c38
5eac02c99456373adc10942c9e9adaf1
Thanks!

**Comment by felder** [comment]
@samwu101 ok I just added your 3 codes.

**Comment by rroggenkemper** [comment]
Sorry this is kinda late, but here are my codes:
add4f14e61b549bb26aaac1ec05e97a3
6edae5baf9b08066df2ca99ecc2c1bf3
23f3ac405063c21b23275504ca45ab2b

**Comment by Yanay1** [comment]
Updated Codes:
5b9e64abdebeca5d617822381744744b
a7b92e1bffedf669c8301f76e617f255
bce998e3f793c84d635d63b0122c662d

Thanks!

**Comment by kvah** [comment]
Sorry, my 8.2 and 8.3 codes were correct but I accidentally provided my SJCC code for 8.1 Here's the correct code for 8.1

4da3ae20c3f95786fce26c8b92d37a60

**Comment by felder** [comment]
@kvah which code does your updated one replace?

**Comment by felder** [comment]
@Yanay1 do the updated codes replace all 3 of your previously posted ones?

**Comment by Yanay1** [comment]
Yeah, thanks!

**Comment by kvah** [comment]
@felder 
This code: 86ee7c6a0956500bcd6ef979adb19a59
should be replaced with this one: 4da3ae20c3f95786fce26c8b92d37a60

**Comment by felder** [comment]
@kvah @Yanay1 thanks.  I'll get all these codes entered shortly.

**Comment by felder** [comment]
Codes have been entered.  I believe that's everyone, so I'm going closing this.
