### ISSUE TITLE
Document adding DNS entries

### ISSUE THREAD

**Issue by yuvipanda** [berkeley-dsep-infra/datahub#535]
We have permissions to make DNS entries under *.datahub.berkeley.edu and *.data8x.berkeley.edu. 

- [ ] Document who has access to this
- [ ] Document how to get access to this
- [ ] Document how to add / remove an entry

**Comment by ryanlovett** [comment]
@yuvipanda has access to .data8x. I *think* he has access to .datahub too but I'm not sure.

**Comment by yuvipanda** [comment]
Fixed in #541
