### ISSUE TITLE
URL generator:

### ISSUE THREAD

**Issue by rainwoodman** [berkeley-dsep-infra/datahub#55]
Is there a way to clone and launch a private repo from github? 

We are developing homework /solutions on a private repo before staging them out to the public repo. It could be nice if we can one-click launch a private repo. I believe we can probably do so by adding a SSH key to our account of the data8 instances? Or may be we can grant a github authorization for data8 in the repo?

**Comment by yuvipanda** [comment]
Is this just for development? If so you can just use a key in your local
home directory on the hub to do pushes. For students, I think it is best to
push from a private repo to a public repo and have them pull from that. We
use public image repositories, so we don't really have any secure way to
access private repos. Philosophically too I personally prefer having public
repos :)

Have you considered having a simple automated script that can auto push to
the public repo each time you push to the private one? We can probably help
with that if need be.

/Cc @ryanlovett and @gunjanbaid

**Comment by rainwoodman** [comment]
Thanks. I think pulling from a datahub instance is a good practice. The HW solutions shall not be public before the homework is due, but if multiple people are testing it then it must be hosted privately..

**Comment by rainwoodman** [comment]
Since a better alternative is provided (directly clone the private repo from terminal interface), I will close this issue.
