### ISSUE TITLE
Notebook cannot connect to julia kernel

### ISSUE THREAD

**Issue by ryanlovett** [berkeley-dsep-infra/datahub#551]
A user in the math124 deployment reported that they couldn't connect to the Julia kernel in notebook. I verified this and the same is true with lab. They can use the python kernel however. I was able to replicate this with my own pod and by starting another server's pod. This is not unique to a particular node.

Edit: I can run julia from the terminal.

**Comment by yuvipanda** [comment]
My suspicion is memory usage. But notebook logs will give us a better idea... Would be great if you have time to take a look. If not I can on monday

**Comment by yuvipanda** [comment]
thanks, @ryanlovett! Does this happen to your pod too?

**Comment by ryanlovett** [comment]
It did happen for both you and I on Friday, but I couldn't reproduce by Sunday, other than in the user's account.

**Comment by ryanlovett** [comment]
This isn't happening anymore. Closing for now.
