### ISSUE TITLE
Secure Data

### ISSUE THREAD

**Issue by ericvd-ucb** [berkeley-dsep-infra/datahub#573]
An instructor today asked me about using restricted/sensitive/proprietary Data - I was thinking like instead of using github to host the data maybe in certain cases the instructor could have the data hosted somewhere internal to the Datahub, and students could call it and analyze it, but it wouldn't be out there like in public Github.  Maybe this would be like a special case of the very large datasets like in the Cogneuro case

**Comment by ryanlovett** [comment]
This is technically possible. This is what I told @ktakimoto when it was a professor's research team (not a class) that had asked about hosting sensitive data:

> If there is proprietary data in the cloud, the hub would have to be registered in campus' [RDM system](https://security.berkeley.edu/services/netreg/documentation/register-restricted-data-applications).
> 
> I'm somewhat nervous about facilitating this due to the risk involved and not knowing what the agreement is between the data vendor and the person who obtained the data. Pedagogically one can teach students how to work with proprietary data without the data actually being proprietary. However, this doesn't sound like an instructional use case. If so, I think in the short term they should probably be using Research IT's JupyterHub on savio and engage with RIT staff to secure the data. Long term we might discuss how to best support courses with this need and then perhaps researchers too.

**Comment by yuvipanda** [comment]
Based on conversations here, offline and elsewhere - I think the current recommendation is to not put any such 'secure' data on our datahubs. Other options to consult would be:

1. Find credits to get yourself a VM (I think the discovery program at DSEP has some credits for this purpose)
2. Contact research IT to see which of the many services they offer can best fit this.

Thanks!
