### ISSUE TITLE
Give Jon Felder DNS access

### ISSUE THREAD

**Issue by yuvipanda** [berkeley-dsep-infra/datahub#577]
Hey @ryanlovett. Can you give @felder DNS access when you have the time? Thanks!

**Comment by ryanlovett** [comment]
I've added him to edu:berkeley:org:nos:DDI:datahub. Jonathan, can you try [logging in to infoblox](https://docs.datahub.berkeley.edu/en/latest/howto/dns.html)?

**Comment by felder** [comment]
@ryanlovett I was able to login and modify the necessary records.
