### ISSUE TITLE
Package request: emcee on phy151 server.

### ISSUE THREAD

**Issue by rainwoodman** [berkeley-dsep-infra/datahub#58]
We are investigating using emcee in phy151 course work. Could you help us to deploy the package to the instances?

BTW: I tried a pip install --user emcee but the notebook kernel can't find it afterwards.

**Comment by gunjanbaid** [comment]
Will be added by https://github.com/berkeley-dsep-infra/datahub/pull/59. Will post an update when it's merged into datahub.

**Comment by gunjanbaid** [comment]
@rainwoodman This has been done, you can now use `emcee` on datahub.
