### ISSUE TITLE
Current Theano incompatible with current NumPy

### ISSUE THREAD

**Issue by charlesfrye** [berkeley-dsep-infra/datahub#608]
As detailed in [this issue for pyMC3](https://github.com/pymc-devs/pymc3/issues/3340) and fixed in [this PR for Theano](https://github.com/Theano/Theano/pull/6671), the combination of `theano<1.0.4` and `numpy>=1.16` is incompatible. All compiles fail.

Would it be possible to update Theano to the latest version? This should happen if pyMC3 is updated to the latest version, which would also be nice. Thanks!

**Comment by charlesfrye** [comment]
This would be for the class `psych101d`. I didn't follow the fork-and-pull model from the [curriculum guide](https://berkeley-data.gitbook.io/curriculum-guide/during-the-course/python-packages) because it would require changes to the requirements of two other courses: [phys151](https://github.com/berkeley-dsep-infra/datahub/blob/fa41edd43bc182c1de8969dbd9e3c5e186a10bba/deployments/datahub/image/requirements.txt#L67), which requires `pymc3==3.2` and [data-x](https://github.com/berkeley-dsep-infra/datahub/blob/fa41edd43bc182c1de8969dbd9e3c5e186a10bba/deployments/datahub/image/requirements.txt#L80), which requires `Theano=0.9.0`, and I wasn't sure what the protocol would be.

**Comment by ryanlovett** [comment]
Hi @charlesfrye,

Thanks for checking for dependency conflicts! Unfortunately we have no good protocol for this in the short term. There are two options:

1. Have students run `pip install package==version` manually each time they start a new server, or
2. Contact the instructors of the other courses and ask whether the proposed upgrade would conflict with their environments. As I understand it, you're asking for pymc3==3.6 and theano==1.0.4 ? I believe that physics 151 isn't being taught this semester so we'd just need to find out about 8x and Theano..

**Comment by charlesfrye** [comment]
Hi @ryanlovett.

It'd be preferable not to have the users install: Theano is a big library on its own; I'd also have to copy the datahub `requirements.txt` to make sure shared dependencies don't get updated (e.g. `numpy1.16.0->1.16.2`), as happens with the simple `pip install package==version` command you suggested. If push came to shove, I think I'd prefer setting up my own (littlest) JupyterHub.

The course won't be taught until the fall, so I can hold off until late summer to get the datahub environment squared away if you expect to have a protocol in place for conflicts by then.

Otherwise:
1. Is it kosher to change environments for classes not being taught, or should I reach out to the phys151 folks? Do you know who those folks are, or where I can find that info?
1. Who should I contact about 8x?

Thanks!

**Comment by ryanlovett** [comment]
Yes, it'd be totally fine to update a dependency if the course isn't being taught. I've reached out to @ericvd-ucb (DS Curriculum Coordinator) for confirmation about the status of both courses.

Should the dependency conflicts be too complex to manage (and I don't think they are just yet), we could easily create a separate hub on the same cluster, i.e. psych101d.datahub.b.e.

**Comment by ericvd-ucb** [comment]
@ryanlovett  - this is a complicated topic!  Charles is asking about a Fall deployment - his starting point was to ask for a separate hub - but my advice was to try to see if the packages could work first and having a separate hub be a second option

Data-X is actually IEOR 135 - I don't know if they are using datahub and it looks like they are [not](https://docs.google.com/spreadsheets/d/1Ib7vmlOTjGe52SWxSD5MvwsZWyuB75ZFMAarb28wZ5s/edit#gid=0)...

Data8x runs on a separate hub, continuously... I dont know who is the instructor of record...Data8 does not use tensorflow and keras....

Physics 151 will run in the Fall I assume - yes I think that we should arrange with them - I am gonna guess that they could use the same version of pymc... but that's just a guess... I can facilitate this conversation

**This is all making me think we need a better and more timely way to manage requirements.txt!**

**Comment by ryanlovett** [comment]
@ericvd-ucb Argh, i conflated 8x and data-x. 😝 

I totally agree with you about the available options. If neither IEOR 135 nor Physics 151 are being taught right now, I think we can go ahead with the package updates. The [Data-X syllabus](https://data-x.blog/syllabus/) does reference Spring '19 and there's an [SIS entry](https://classes.berkeley.edu/content/2019-spring-indeng-135-001-lec-001) for it too, so I'll ask the instructors.

Long term we'll probably [provide separate user images](https://github.com/berkeley-dsep-infra/datahub/issues/476), for courses that need them, on the same hub.

**Comment by ericvd-ucb** [comment]
Yep - The IEOR 135 class is being taught this semester  - it just looks like from the documentation that the class recommends a local conda workflow - and none of the homeworks mention datahub....

**Comment by ryanlovett** [comment]
Ah, good catch! I'll go ahead and update the libraries.

**Comment by drbenvincent** [comment]
Bump. I'm having the problem outlined here https://github.com/pymc-devs/pymc3/issues/3340. I'm not a conda or pip ninja, so the only solution I've found is to totally reinstall my Anaconda Python distribution - which is a bit drastic 😭

**Comment by charlesfrye** [comment]
I am no longer getting this issue in the `prod` environment since the addition of `Theano==1.0.4` to the `requirements.txt`, ([link](https://github.com/berkeley-dsep-infra/datahub/blob/c345dc1bd9886a56e071acf5639150cd8fb9f9cb/deployments/datahub/image/requirements.txt#L103)). This is [to be expected](https://github.com/pymc-devs/pymc3/issues/3340). Are you making any adjustments/installing things with `pip`?

If you run the below on datahub without installing anything, you should see the outputs `'1.0.4'` and `'1.16.0'`. If you see something different, a `pip` or similar command must've changed the environment.
```python
import numpy as np
import theano

print(theano.version.full_version)
print(np.version.full_version)
```

**Comment by drbenvincent** [comment]
Sorry, I think I was a bit hasty with my comment. My issues were PyMC3 and I got here from https://github.com/pymc-devs/pymc3/issues/3340 as the issue was closed, but still causing issues, then referenced in this issue. In my haste I failed to realise this datahub repo is totally independent from what I'm doing with PyMC3. So sorry about that. False alarm / not relevant. I was never here.

**Comment by yuvipanda** [comment]
I think this was sorted out a while ago :D
