### ISSUE TITLE
400 : Bad Request OAuth state missing from cookies

### ISSUE THREAD

**Issue by kareemelbadry** [berkeley-dsep-infra/datahub#611]
I currently can't log in to Datahub. I get the error in the title. I've tried multiple browsers and computers, but that didn't fix it. Some googling reveals related issues (e.g. https://github.com/jupyterhub/jupyterhub/issues/1682), but I can't grok the solution.

**Comment by ryanlovett** [comment]
Can you please delete all datahub.berkeley.edu cookies from your primary browser and try again?

**Comment by kareemelbadry** [comment]
Fixed. Thanks. I had tried deleting cookies earlier unsuccessfully, but I was inadvertently only deleting the recent ones.
