### ISSUE TITLE
500: Internal Server Error logging into datahub

### ISSUE THREAD

**Issue by ktakimoto** [berkeley-dsep-infra/datahub#613]
This was first reported by a GSI using an interact link this afternoon- we've since duplicated it for 7 modules devs trying to access datahub (using interact links or not).

When navigating to datahub, we're seeing the "Sign in with CalnetID" button, then the Calnet login (if not already logged in). After logging in, instead of the notebook dashboard we're getting the 500: Internal Server Error message.

It doesn't seem to be tethered to any particular browsers: we've seen it in Chrome, Firefox, Edge, and Safari, and some users have NOT seen it in Chrome, Safari, and AVG secure browser. 

I'm getting it on Chrome, Firefox, and Edge. Oddly, a version of Chrome that was installed today on one account on my laptop is NOT getting the error. The error is persisting in the other browsers even after deleting all cookies and refreshing the browser (i.e. deleting extensions and resetting to defaults). Ideas?

**Comment by ryanlovett** [comment]
Can you try deleting all datahub cookies?

**Comment by ktakimoto** [comment]
@ryanlovett I've tried deleting all cookies from all time in Chrome, Edge, and Firefox. Am still getting the error in all.

**Comment by ryanlovett** [comment]
@ktakimoto Thanks for trying. More than one hub was affected and killing hub pods got people going again. Still looking into things.

**Comment by kareemelbadry** [comment]
Just want to report that I am having the same problem. Yesterday I temporarily fixed it by deleting all cookies, but today the problem is back and deleting cookies doesn't help.

**Comment by ktakimoto** [comment]
@ryanlovett if this lasts into tomorrow, is there an unaffected hub that could accommodate modules students? Or is Binder our best bet?

We're expecting to have 6 30-40 person discussion sections Monday and Tuesday, and a 150 person lecture Thursday, plus another 40 or so using it asynchronously through the week.

**Comment by ryanlovett** [comment]
Bumped the hub pod again. This didn't manifest itself when I was logged in, only when I logged out and tried to log back in. prob140 was also affected.

After hub pod bump, logging and logging in worked fine.

Root cause is still unknown.

@dibyaghosh

**Comment by ktakimoto** [comment]
Looking good for me- asking modules leads and devs to retest now

**Comment by ktakimoto** [comment]
Reports from modules and connectors folks are positive. Thanks @ryanlovett !

**Comment by ryanlovett** [comment]
Actually I'd like to leave this open until we can figure out the root cause. I feel like this will happen again.

**Comment by robertSweeney** [comment]
@ryanlovett it appears this issue has resurfaced again (not working on my chrome browser and others have reported the issue to me past midnight as well)

**Comment by ktakimoto** [comment]
@ryanlovett Yup, spoke too soon. Just had a passel of SOC-5 students get hit with it. I'm getting it on Edge but not Chrome or Firefox, and logging out/deleting cookies doesn't help.

**Comment by ryanlovett** [comment]
@ktakimoto I'm going to revert a security update from last week because I think it is causing all of this.

https://github.com/berkeley-dsep-infra/datahub/pull/614

**Comment by ryanlovett** [comment]
Okay, the downgrade is complete.

**Comment by ktakimoto** [comment]
@ryanlovett Interesting- the second and third Soc-5 sections (~20 students each) were all able to log in to datahub at 10 and 11, respectively. Not sure what that does/doesn't indicate

**Comment by ryanlovett** [comment]
It probably means that the students hadn't logged out. I'm guessing if they had, and tried to login again, they would have run into this. That's the behavior I was seeing in any case.

I'm going to file an upstream bug later today.
