### ISSUE TITLE
Run hub for ISchool's W261

### ISSUE THREAD

**Issue by yuvipanda** [berkeley-dsep-infra/datahub#637]
UC Berkeley's I School runs a Machine Learning at Scale class - W261 (https://www.ischool.berkeley.edu/courses/datasci/261). This uses spark, and currently requires students to directly try to use Google DataProc. This is far from ideal.

The data sciences division is gonna collaborate with them to run a hub for the course, hopefully for the summer. This issue will track all the things necessary for it to happen.

TODO: 

- [x] Set up w261.datahub.berkeley.edu with Continuous Deployment - @yuvipanda 
- [x] Set up the image to get simple, in-process spark working - @jameswinegar 
- [x] Spark query GCS over HDFS interface - @jameswinegar
- [ ] Spark execute as cluster in k8s - @jameswinegar  
- [x] SparkUI visibility to user - @yuvipanda 
- [ ] Per-user GCS Bucket creation and permission - @yuvipanda 
- [ ] Per-user kubernetes namespace and RBAC - @yuvipanda 
- [ ] Per-user ResourceQuota - @yuvipanda 
- [ ] Review spark-defaults.conf for stability/quality improvements - @jameswinegar 
- [ ] Unit testing - @jameswinegar (https://gist.github.com/jameswinegar/8e1cfeb4f0b4a842f9772de7ba02f3b7)
- [ ] Remove any hacks / fix upstream projects such as repo2docker - @jameswinegar / @yuvipanda 
- [ ] Determine Spark Job submission workflow - @jameswinegar 
- [x] Determine git workflow - @jameswinegar / @kyleiwaniec

**Comment by jameswinegar** [comment]
@yuvipanda we're able to run spark locally on the jupyter pods now.

**Comment by yuvipanda** [comment]
@jameswinegar cool! Is the jdk the only thing needed? No jars or maven setup?

**Comment by jameswinegar** [comment]
@yuvipanda the pip install handles all the py4j management, this does put a JVM locally on the pod. If students keep the code on their individual pod simple, like unit tests then they'll be covered before shipping to the master executor we talked about.

**Comment by yuvipanda** [comment]
@jameswinegar that is awesome! I think next easy win is SparkUI. Can you provide some simple instructions - and maybe a notebook - that will start it and make it accessible from inside the pod locally? I can then work on proxying it to the students.

**Comment by jameswinegar** [comment]
@yuvipanda here's the notebook I used to test it worked locally. It prints the internal DNS for the UI as a hyperlink as well. 

https://drive.google.com/file/d/1uOcH6rij1QSjUnCYn8O85-SUH9IoXe8v/view?usp=sharing

**Comment by yuvipanda** [comment]
Based mostly on work in https://github.com/jupyterhub/jupyter-server-proxy/issues/57 by @h4gen and @ryanlovett, I've now built https://github.com/yuvipanda/jupyter-sparkui-proxy that should let you access spark UI from inside JupyterHub. https://gist.github.com/yuvipanda/c1df43456edcecefc78cf0ba47c59c33 is a sample notebook. Once you run this, you should be able to go to:

https://w261.datahub.berkeley.edu/hub/user-redirect/sparkui

to see your spark UI. We might wanna put a button or something in the UI eventually. 

I also discovered that spark UI doesn't auto update live, which makes me appreciate dask much more.

**Comment by jameswinegar** [comment]
Started the work on getting Spark running with GCS integration on a pod. Hoping to get it done this weekend.

**Comment by jameswinegar** [comment]
GS works with HDFS now. Working on Spark.

```
jovyan@a7e0bb5f35d7:~$ hdfs dfs -ls gs://w261-testing
Found 2 items
-rwx------   3 jovyan jovyan    1002356 2019-04-28 05:26 gs://w261-testing/GCP_Data_Eng.pdf
-rwx------   3 jovyan jovyan       2536 2019-04-28 05:55 gs://w261-testing/stats.csv
```

**Comment by jameswinegar** [comment]
@yuvipanda I'm able to get Spark/HDFS to work with GCS when the container is not running inside k8s. When the container is launched inside k8's the Spark and Hadoop directories are gone and it's just my user notebook. I'm guessing this is because of how you're handling NFS mounts.

I originally tried to install Spark/HDFS into the /srv directory but ran into permission issues. Would there be a location outside of $HOME that we can put these services during the postBuild phase?

**Comment by jameswinegar** [comment]
We have some hacks around where to mount the file currently. Once we get repo2docker fixes made we can address those and focus on the dynamic resource generation. I'll focus on getting the pods to run in a clustered setup.

More robust testing notebook: https://gist.github.com/jameswinegar/8e1cfeb4f0b4a842f9772de7ba02f3b7

**Comment by yuvipanda** [comment]
repo2docker PR is https://github.com/jupyter/repo2docker/pull/657

**Comment by yuvipanda** [comment]
The repo2docker PR has been merged, and should be part of a 0.9 release coming out soon. I've picked it up in our circle config for now.

With #661 we also have given user pods on w261 more rights on their own namespace. This should let them scale out spark clusters. Once we know this is working, we can go on and lock this down.

**Comment by jameswinegar** [comment]
Given some of the time crunch I've had I think we should refocus from next week to Fall semester. Students will use GCP again this semester.

**Comment by yuvipanda** [comment]
@jameswinegar ah, ok. sorry we couldn't get this done in time.

I'll extract out the work we did into a generalized form regardless, and see if I can deploy it in a different project. Makes life easier in the fall.

**Comment by yuvipanda** [comment]
This hasn't moved in a while, so I'll close it for now. Let's re-open if we're doing this again :)
