### ISSUE TITLE
Update TensorFlow to support the official tutorial

### ISSUE THREAD

**Issue by TonyLianLong** [berkeley-dsep-infra/datahub#642]
As currently tested on the DataHub, the version of TensorFlow is 1.3.0, which does not support `tf.keras` and is not compatible with the official tutorial link in Data 8 Project 3 (https://www.tensorflow.org/tutorials/), though the use of TensorFlow is optional for completing this project. Any steps to update the TensorFlow version?

**Comment by yuvipanda** [comment]
This has been done.
