### ISSUE TITLE
Econ172 looking for ivpack or AER

### ISSUE THREAD

**Issue by ericvd-ucb** [berkeley-dsep-infra/datahub#643]
Hi
ECON 172 would like the R packages
AER and ivpack

Thanks
Eric

**Comment by ericvd-ucb** [comment]
For some reason install.packages() isnt working with these....

**Comment by ryanlovett** [comment]
Can you test on staging and let me know?

**Comment by ericvd-ucb** [comment]
Tested on Staging and Passing!
Thanks so much

**Comment by ryanlovett** [comment]
Fixed by #644.
