### ISSUE TITLE
Move datahub gofer-grader from a separate VM to kubernetes

### ISSUE THREAD

**Issue by felder** [berkeley-dsep-infra/datahub#659]
Currently the gofer-grader for datahub runs in a separate VM.  Jupyterhub was then configured to contact the grader via the VM's GCP's internal DNS name ("grader").

For whatever reason, that internal DNS name stopped resolving which caused a grader outage.  A workaround of using a static IP brought the grader back online, but ultimately the solution to this issue and other potential issues with the gofer-grader is to move it into the kubernetes cluster.  This way it will scale and kubernetes can make sure it's always available.

The gofer-grader consists of a service which accepts requests for grading and a library that gets spun off in a docker container that does the grading.

https://github.com/data-8/Gofer-Grader

Each datahub cluster could have its own pod that runs both the gofer-service and docker along with some form of persistent storage.

**Comment by yuvipanda** [comment]
Thanks for opening this!

I think the way to do this is to have a Pod with two containers:

1. The gofer grader container
2. A Docker-in-Docker (DIND) container https://hub.docker.com/_/docker

This lets us treat a pod as equivalent to a VM with two processes talking to each other. This is how mybinder.org uses docker, for example.

This Pod would be managed by a kubernetes Deployment object, so it can be auto spawned and restarted when needed. If there is no local filestorage state needed (I believe it is an option that is turned on right now, but depending on wether it has been used in the last 6 months or not we can maybe make it optional?), we can run multiple copies when needed.

A Service object would then route requests to this Pod, and JupyterHub would be able to talk to this service endpoint.

This entire setup should be its own helm chart that we can depend on from the 'hub' chart here, turning it off and on per-hub. That'll also allow it to be tested without being dependent on a hub.

How does this sound?

**Comment by felder** [comment]
Sounds reasonable to me.  My concern around persistent storage has to do with whether or not the submissions need to be saved for any reason.

**Comment by yuvipanda** [comment]
@felder right. I think if they *do* need to be saved for some reason, they should be using object storage like GCS rather than the file system. That could be a next step though.

**Comment by yuvipanda** [comment]
Gofer is dead!
