### ISSUE TITLE
Connect with instructional designer at DLS for Canvas conversion

### ISSUE THREAD

**Issue by anthonysuen** [berkeley-dsep-infra/datahub#663]
Connect Joseph Kearns, the instructional designer at DLS that will be moving the content over to Canvas from Data 8X on edX

**Comment by yuvipanda** [comment]
https://docs.datahub.berkeley.edu/en/latest/instructor/howto/bcourses.html is now detailed docs on how to use canvas with the hub. Hope this helps, @anthonysuen
