### ISSUE TITLE
Run hub for iSchool W266 (NLP)

### ISSUE THREAD

**Issue by jameskunz** [berkeley-dsep-infra/datahub#702]
W266 uses python with tensorflow

- [ ] Base level datahub
- [ ] Lab as default
- [ ] Tensorflow 
- [ ] TensorBoard Proxy?

**Comment by jameswinegar** [comment]
@yuvipanda looks like there is some requirements overlap with data-x
https://github.com/berkeley-dsep-infra/datahub/blob/staging/deployments/datahub/image/requirements.txt#L76

TF 1.3.0 is pretty old (Aug 16, 2017) latest stable is 1.13.

**Comment by jameskunz** [comment]
Our assignments require at least 1.10 this semester, though maybe some of the later one will use the beta 2.0 api...  so some flexibility on what's provisioned will be helpful!

**Comment by yuvipanda** [comment]
@jameskunz are you still interested in doing this?

**Comment by yuvipanda** [comment]
There is now an ischool.datahub.berkeley.edu
