### ISSUE TITLE
Run hub for iSchool w241 (Experiments and Casual Inference)

### ISSUE THREAD

**Issue by d-alex-hughes** [berkeley-dsep-infra/datahub#705]
This course is current being run on a datahub instance, with the help of @ryanlovett. Things are running smoothly and efficiently, but if there is an option to migrate into a unified instance for the School of Information, that too would be great. 

The only requirement is an Rstudio instance that matches the current prod Rstudio.

**Comment by yuvipanda** [comment]
Thanks for opening this, @d-alex-hughes! I think for now, you can continue using datahub as before. I'll let you know if we have a unified JupyterHub for R users (possible?), one for ischool (I don't think we wanna do this) or something like that. RStudio will continue to work as is in datahub.berkeley.edu for the foreseeable future.

**Comment by d-alex-hughes** [comment]
Of course, thanks for taking the time to meet to talk about this today. Because there's no additional action to take against this, feel free to close the issue!

**Comment by yuvipanda** [comment]
@d-alex-hughes I've some questions about how you distribute 'materials' to your students though. Do you have them in a git repo? Do students 'git clone' them? Are you using nbgitpuller?

**Comment by jameswinegar** [comment]
@d-alex-hughes #762 #761

**Comment by yuvipanda** [comment]
@d-alex-hughes there's now an r.datahub.berkeley.edu that launches users directly into RStudio (although notebook is also available). It has a newer version of R, and is based on the R community maintained [rocker](https://www.rocker-project.org/) project. It also has a lot more libraries installed

We're working on figuring out if any libraries are missing, and adding them. Do take it for a spin!

**Comment by yuvipanda** [comment]
There is now an ischool.datahub.berkeley.edu
