### ISSUE TITLE
Run hub for Ischool's W203 (Statistics for Data Science)

### ISSUE THREAD

**Issue by paul-laskowski** [berkeley-dsep-infra/datahub#707]
We're interested in using a hub environment for our introductory statistics class.  Our class uses R running in Jupyter notebooks (and students sometimes use RStudio with Rmd files). 
 Most datasets are small (1 million rows or less).  The course comes before w241 and likely needs a very similar or even identical set of libraries.  Our assignments and live session notebooks are hosted on a set of private Github repositories.

Thanks you!
Paul

**Comment by jameswinegar** [comment]
@yuvipanda should be the same as #705

**Comment by yuvipanda** [comment]
Thanks for opening this, @paul-laskowski! I guess the major difference is the private GitHub repository? Does that always need to be private? How often does it get updated?

**Comment by paul-laskowski** [comment]
Hi @yuvipanda!  Yes, we currently rely on private repos.  There are a few reasons, but one is that we control access to our solution notebooks in this way.  We have a separate repo for each homework and each live session and a corresponding solution repo for each of those.  For each repo, we would typically push a few updates in the week or two before giving students access.

**Comment by jameswinegar** [comment]
@paul-laskowski #761 #762

**Comment by yuvipanda** [comment]
@d-alex-hughes there's now an r.datahub.berkeley.edu that launches users directly into RStudio (although notebook is also available). It has a newer version of R, and is based on the R community maintained [rocker](https://www.rocker-project.org/) project. It also has a lot more libraries installed

We're working on figuring out if any libraries are missing, and adding them. Do take it for a spin!

Are you requiring users to just *pull* from a private repository or also to push to them? If it's the former, we can create a 'deploy key' and give people access to just those to pull from.

**Comment by paul-laskowski** [comment]
Hi everyone, sorry it's been months!  We have new students entering the stats class right now, and I'm wondering if we can direct them to datahub.berkeley.edu for their computing needs.  To reply to Yuvi, we currently only have students pull from our repositories.  For submission, we use a separate 2U system.

**Comment by yuvipanda** [comment]
@paul-laskowski are you still interested in this? Sorry for the late response :D Happy to have you use it! There's also `r.datahub.berkeley.edu` that is probably a good place :)

**Comment by paul-laskowski** [comment]
Hi Yuvi, Good to hear from you!  Our current situation is we are directing
our students to r.datahub.berkeley.edu as the recommended computing
environment for our stats class.  I don't have numbers, but I would guess
that a substantial fraction of students are going this route (maybe 20-50
students).  Most of our assignment notebooks are in private repos, so it
would still be great if there was a more slick system for opening these
notebooks with a click, instead of opening a terminal and running git
commands.  I feel like it's been a while, so I don't know the latest that
your team has been up to :)
Best,
Paul

**Comment by yuvipanda** [comment]
@paul-laskowski great to hear! We added support for private repos recently - check out https://docs.datahub.berkeley.edu/en/latest/users/private-repo.html :) Please tell your colleagues too!

I'm gonna close this issue for now. Please feel free to file new ones if necessary.

Thanks!
