### ISSUE TITLE
Run hub for iSchool's W207 (Intro to Applied Machine Learning)

### ISSUE THREAD

**Issue by todd450** [berkeley-dsep-infra/datahub#723]
Let me know if you need any other info.  Thank you!

**Comment by yuvipanda** [comment]
Thanks, @todd450. Can you tell us the timeline for this? That'll help plan for what more information is needed.

Thanks!

**Comment by jameswinegar** [comment]
@yuvipanda, it has pretty vanilla requirements. Sklearn, matplotlib, pandas, etc. Likely the existing python environments in datahub fit the bill. The data sets aren't large so normal capacity should be fine as well.

**Comment by yuvipanda** [comment]
ah cool. @todd450 you can check out datahub.berkeley.edu and see if it works for you now. We'll want to list your specific requirements later, but you can '!pip install' stuff to check it out.

**Comment by yuvipanda** [comment]
There is now an ischool.datahub.berkeley.edu :)
