### ISSUE TITLE
Install ffmpeg package

### ISSUE THREAD

**Issue by ericvd-ucb** [berkeley-dsep-infra/datahub#724]
Burkhard Militzer is requesting ffmpeg
for a fall edtion of EPS 109

https://pypi.org/project/ffmpeg-python/
pip install ffmpeg-python

**Comment by yuvipanda** [comment]
Thanks, @ericvd-ucb.

@felder do you think you'll have time to work on this?

**Comment by felder** [comment]
@yuvipanda yeah I should be able to do this

**Comment by ericvd-ucb** [comment]
hi @felder - sorry to bug you ... i just want to get back to the instructor about this at some point  - thanks so much!

**Comment by felder** [comment]
@ericvd-ucb Does the instructor need this now?  My thoughts were that this was not high priority for immediate installation because it's for the Fall.

**Comment by ericvd-ucb** [comment]
@felder  its not urgent .... but they are looking to figure out if the hub is going to work for their fall class and test out the workflow in advance. ( and unfortunately the way they run the notebooks to do animations on a local Jupyter doesnt work on the web/hub Jupyter)  Let me phrase it another way... could you give me a ballpark estimate of when this package install might happen in the future so I can report back?

**Comment by felder** [comment]
@ericvd-ucb I'm going to meet with @yuvipanda tomorrow and the current plan is to do this work then.  So, optimistically you can expect the install might happen tomorrow afternoon.  I'll update you on the progress either way.
