### ISSUE TITLE
Cleanup datahub image

### ISSUE THREAD

**Issue by yuvipanda** [berkeley-dsep-infra/datahub#725]
The datahub image is too big and too unweildy. It also has packages and images
that are no longer required for classes that are no longer taught. Let's clean it up.

Classes currently with lots of special handling:

- [ ] CogNeuro. Not offered since Spring 2018 (https://classes.berkeley.edu/search/class/cogneuro?retain-filters). Uses NeuroDebian
- [ ] cp255. Lots of Geo stuff, many disabled. Last offered Spring 2017. https://classes.berkeley.edu/search/class/cp255?retain-filters=1
- [ ] ds100. Has its own hub.

**Comment by ryanlovett** [comment]
I've checked with the prof for stat 159/259 about their dependencies.

**Comment by yuvipanda** [comment]
@ryanlovett for R, I'm thinking of doing the following:

1. Remove all apt packages
2. Use repo2docker to get R / IRkernel
3. Install individual packages folks want with install.R

Do you know where the current list of R packages came from?

**Comment by ryanlovett** [comment]
@yuvipanda Using install.R will be much slower because it has to compile every package. This would also require installing additional build dependencies (e.g. -dev packages) into the image though that's less of an issue. Personally I'd rather stick to apt packages if possible. One reason for not using apt is if the package version is too old.

All R packages were requested by @ericvd-ucb on behalf of instructors. Some dependencies of those packages were explicitly specified as apt packages where possible, to reduce build times.

**Comment by ryanlovett** [comment]
@yuvipanda From experience I'd guess that using install.R for most R packages would add about ~ 20 min per build. It'd be worth checking though if/when you create the PR.

**Comment by yuvipanda** [comment]
@ryanlovett this is tempting me to make a new R specific hub, that we can fold into a different image eventually.

**Comment by ryanlovett** [comment]
Short term it'd require less development than adding a second image to the hub and enabling interact links to invoke the image. The only downside is that people might get used to the temporary R-based hub name.

I think the current classes that use python don't also use R, and vice versa. By the time we're handling those courses we'll be able to accommodate them with custom images.

**Comment by yuvipanda** [comment]
@ryanlovett yeah, I like it. I'm a little torn on apt vs install.R, but we can probably move that for later.

**Comment by ericvd-ucb** [comment]
Totally Open to the R specific Hub - Noone is using Python and R  ( yet)  -  Issues might be 1) the already mentioned getting used to an R hub name that is less permanent  2) students start having files in multiple places instead of one single place.  Both seem minor

**Comment by yuvipanda** [comment]
What I'd like to do if we have an R specific hub is to still share home directories between that and datahub. I think that should make this easier, and we can solve (1) with redirects later.

**Comment by ericvd-ucb** [comment]
Yes - I think there is a lot of potential for an R hub, and I want to talk this through with @ryanlovett on how to support more stats classes in the future.  I could see a role for many stats classes where they recommend "install R studio on your laptop" but the R datahub is there as a backup... or for students with chromebooks, etc.  ( sorry if this isnt quite the place for this discussion - hooray for cleaning up requirements.txt )
