### ISSUE TITLE
Make an R hub

### ISSUE THREAD

**Issue by yuvipanda** [berkeley-dsep-infra/datahub#729]
Eventually this will be a profile on datahub. But right now, i think we should have an R hub.

It should:

1. Use repo2docker
2. Start into rstudio by default
3. Figure out where the R should come from. I'm hesitant for it to be from apt.
4. Share home directories with main datahub

Split off from #725.

**Comment by ericvd-ucb** [comment]
Is this the right place for Python R kernel to be as well?

**Comment by ryanlovett** [comment]
@ericvd-ucb I think so.

@yuvipanda Re: 3, what are your pros and cons for not using apt for R?

**Comment by jameswinegar** [comment]
Why not just use CRAN directly instead of Ubuntu for apt? This gives pre-compiled binaries and latest version. Can drop to install when not available.

```
# apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
# apt-add-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu bionic-cran35/'
# apt install r-base-dev
# R

R version 3.6.0 (2019-04-26) -- "Planting of a Tree"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)
...
> R.version
               _                           
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          3                           
minor          6.0                         
year           2019                        
month          04                          
day            26                          
svn rev        76424                       
language       R                           
version.string R version 3.6.0 (2019-04-26)
nickname       Planting of a Tree 

```

**Comment by ryanlovett** [comment]
@jameswinegar CRAN has very few binary packages -- just enough to cover a basic install.

https://cloud.r-project.org/bin/linux/ubuntu/bionic-cran35/

At one point the c2d4u ppa was building a lot of packages, but not so much for newer Ubuntu releases. Even then, the ppa had rolling builds so they weren't reproducible. There's more info, links, conversation, etc. at https://github.com/jupyter/repo2docker/issues/412.

**Comment by ericvd-ucb** [comment]
Please let me know your timeline on this when and if you have one - I just met with a summer session class who would like to use ( in whatever form is available this summer)

**Comment by yuvipanda** [comment]
@ericvd-ucb they should continue using datahub for summer. The base R packages aren't going away at least until fall.

**Comment by yuvipanda** [comment]
I've thought about this a little more, and I am now convinced fully we should have an r.datahub.berkeley.edu that opens up R Studio by default. It should share home directories with datahub. This sends a very strong signal that we support R equally, and it doesn't play second fiddle to Python. I think this social signal is important enough for us to do this.

I'll get started on this shortly.
