### ISSUE TITLE
Install Cartopy for EPS 88

### ISSUE THREAD

**Issue by ericvd-ucb** [berkeley-dsep-infra/datahub#732]
Can you please install Cartopy ( current version is 0.17)
@swanson-hysell is using it for EPS 88 which will teach in Fall but is doing development for the course over the summer

**Comment by felder** [comment]
@ericvd-ucb The plan is to install this at the same time as the ffmpeg install.

**Comment by felder** [comment]
@ericvd-ucb ffmpeg is being deployed, but I did not get a chance to deploy this.  I will do this tomorrow.

**Comment by Swanson-Hysell** [comment]
I still get this `ModuleNotFoundError`. Will it still be a while before the module is available?

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-a4ba129e3112> in <module>
----> 1 import cartopy

ModuleNotFoundError: No module named 'cartopy'
```

Thanks.

**Comment by felder** [comment]
@Swanson-Hysell It's deploying to the staging hub right now.  After that I'll check it and then it'll probably be another 30m or so before it gets deployed to production.

**Comment by felder** [comment]
@Swanson-Hysell  You should now be able to import Cartopy.

**Comment by Swanson-Hysell** [comment]
Indeed, I now can. Thanks!
