### ISSUE TITLE
Update to matplotlib 3.1.0

### ISSUE THREAD

**Issue by davidwagner** [berkeley-dsep-infra/datahub#740]
Can we update to `deployments/datahub/image/requirements.txt` to use `matplotlib==3.1.0` instead of `matplotlib==2.0.0` and push to staging, so we can test this?

Rationale: We recently ran into an issue with histograms and the datascience package, documented in https://github.com/data-8/datascience/issues/351.  It looks like updating matplotlib fixes this.

I'd like to see if we can fix this before the summer class starts.

(I would have created a pull request, but I don't seem to have access to this repo and thus can't quite figure out how to create a pull request.)

**Comment by ryanlovett** [comment]
Fixed by #742.
