### ISSUE TITLE
QGrid nbextension not enabled

### ISSUE THREAD

**Issue by chrispyles** [berkeley-dsep-infra/datahub#752]
We are trying to get a notebook set up using the qgrid package for a module, however, when we try to look at the widgets they do not render unless we run the shell command below in a cell and then refresh the notebook. Before/after screenshots included below.

`!jupyter nbextension enable --py --sys-prefix qgrid`

Every time the server gets restarted this command needs to be run again, which will be a problem for students who need to pick up on assignments later and find that their spreadsheets are not displaying.

Is it possible to make this extension enabled for students by default when their server starts so they don't need to worry about running shell commands and refreshing notebooks each time?

<img width="1162" alt="Screen Shot 2019-06-14 at 7 49 41 PM" src="https://user-images.githubusercontent.com/40970945/59546155-b5c4c900-8edd-11e9-9fa4-f3854a53a05d.png">

<img width="1154" alt="Screen Shot 2019-06-14 at 7 49 52 PM" src="https://user-images.githubusercontent.com/40970945/59546156-b78e8c80-8edd-11e9-975c-acda30d1b508.png">

**Comment by yuvipanda** [comment]
Thanks for opening this, @chrispyles.

@felder do you wanna do a quick pairing session on this?

**Comment by yuvipanda** [comment]
@chrispyles so @felder is gonna hopefully get this done later today.

**Comment by felder** [comment]
```
!jupyter nbextension list

Known nbextensions:
  config dir: /srv/app/venv/etc/jupyter/nbconfig
    notebook section
      jupyter-matplotlib/extension  enabled 
      - Validating: OK
      nbresuse/main  enabled 
      - Validating: OK
      jupyter-js-widgets/extension  enabled 
      - Validating: OK
      nbextension-scratchpad/main  enabled 
      - Validating: OK
      jupyter-gmaps/extension  enabled 
      - Validating: OK
      qgrid/extension  enabled 
      - Validating: OK
    tree section
      jupyter_server_proxy/tree  enabled 
      - Validating: OK
      nbzip/tree  enabled 
      - Validating: OK

```
