### ISSUE TITLE
Cannot download multiple files from root

### ISSUE THREAD

**Issue by mowilk** [berkeley-dsep-infra/datahub#753]
When trying to download multiple files from root (check the box next to multiple files, then click the zip download button in upper right corner), the page loads for a minute or two, then goes to a 504 Bad Gateway error page. This error only occurs using the zip download button at the root. Everything works fine once I go into a folder.

**Comment by yuvipanda** [comment]
I'm *guessing* this is from the [nbzip](https://github.com/data-8/nbzip) notebook extension. I don't know who is maintaining it still. @ryanlovett / @saladraider?

**Comment by ryanlovett** [comment]
I'm not the maintainer, I just have commit rights and pushed out the last release and oh dear am I the maintainer.

The behavior you describe sounds like the zip is [timing out](https://github.com/data-8/nbzip/issues/17).

**Comment by ryanlovett** [comment]
Closing due to age. Please reopen if this is still a problem.
