### ISSUE TITLE
Outdated dplyr package causing error in summarize

### ISSUE THREAD

**Issue by chrispyles** [berkeley-dsep-infra/datahub#774]
The version of dplyr installed on the hub is causing an error to be thrown because of a deprecated base R function call (screenshot below). Is it possible to get dplyr updated? I researched the error and it seems that dplyr needs to be updated to version 0.7.7 ([link](https://github.com/r-lib/rlang/issues/674)). 

<img width="1123" alt="Screen Shot 2019-06-21 at 9 03 46 AM" src="https://user-images.githubusercontent.com/40970945/59935820-7fb6a600-9403-11e9-8ec3-7fdb265b10e0.png">

**Comment by ryanlovett** [comment]
Fixed by #777.
