### ISSUE TITLE
Request python package mcautograder for class Data 88

### ISSUE THREAD

**Issue by chrispyles** [berkeley-dsep-infra/datahub#783]
**Which package do you want installed?**

mcautograder

**Which class will use this package?**

[Data 88](https://classes.berkeley.edu/content/2019-fall-data-88-001-sem-001)

Include a link to appropriate entry in https://classes.berkeley.edu/ if available. If not, please mention class name & instructor.

**Which semester will this package be used for?**

Fall 2019

This helps us clean up unused packages after a term ends.

**Any additional information we should know about?**

**Comment by felder** [comment]
mcautograder 0.0.5 has been installed.
