### ISSUE TITLE
Install voila package on datahub

### ISSUE THREAD

**Issue by chrispyles** [berkeley-dsep-infra/datahub#784]
Is it possible to get voila \([https://github.com/QuantStack/voila](https://github.com/QuantStack/voila)\) enabled on the Hub? There is an app we want to run for Data 88 in Fall 2019 using it.

**Comment by ryanlovett** [comment]
I think so. It depends on [jupyter_server](https://github.com/jupyter/jupyter_server/) which has the note:
> jupyter_server is an early developer preview, and is not suitable for general usage yet. Features and implementation are subject to change. Please use the stable notebook server for production usecases.

Just in case you weren't aware... We can install it regardless.

**Comment by chrispyles** [comment]
There is also [appmode](https://github.com/oschuett/appmode) if that's a better alternative.

**Comment by yuvipanda** [comment]
@ryanlovett it is an optional dependency, we can just use the serverextension instead. It depends on jupyter_server only if you want to run it in standalone mode, which we don't wanna anyway

**Comment by ericvd-ucb** [comment]
Hey @ryanlovett can we bump this up? not urgent but still desired

**Comment by ryanlovett** [comment]
@ericvd-ucb voila pulls in jupyter_server as an install dependency and that is breaking nbpdfexport.bundler. I need to figure out why...

**Comment by yuvipanda** [comment]
This is present now.

**Comment by yuvipanda** [comment]
Voila was removed (see https://github.com/berkeley-dsep-infra/datahub/issues/2688#issuecomment-912457069).
