### ISSUE TITLE
Moving from Google Authenticator to Canvas Authenticator for all hubs

### ISSUE THREAD

**Issue by yuvipanda** [berkeley-dsep-infra/datahub#787]
# Current authentication

When a user goes to datahub.berkeley.edu (or any of the other on-campus hubs), they are asked to log-in via [Google Authentication](https://github.com/jupyterhub/oauthenticator/blob/master/oauthenticator/google.py). This works because all berkeley students have a Google account via [bconnected](https://bconnected.berkeley.edu/). We validate that the Google account belongs to @berkeley.edu before letting the user in.

This is very simple to build and maintain, since Google OAuth is very popular across a wide variety of domains. 

# Proposed authentication

Instead, I propose we move to authenticate using [bcourses](https://bcourses.berkeley.edu). This is a [Canvas](https://github.com/instructure/canvas-lms) instance, and we will use [Canvas OAuth](https://canvas.instructure.com/doc/api/file.oauth.html) api to authenticate.

This will let in exactly the same set of people who were able to get in via Google Auth, and have the exact same authentication flow as we do now. 

During this switching process, we will not be doing anything else - just do the auth switch. However, this enables a rich set of integrations, primarily by allowing us easy access to the rich canvas API. Examples of things we can do in the future:

1. Ability to provide different environments, limits and other customizations based on the courses a student is enrolled in. 
2. Letting instructurs use Canvas Files as a way to distribute template notebooks and other materials (one-way) to students. This removes the currently required complexity of learning Git / GitHub from instructors, helping us bring this experience to more non-heavily-CS spaces.
3. Automate uploading completed student notebooks into a Canvas assignment as a filtered PDF. This lets instructors integrate manual grading of notebooks into their existing workflows if they're already using bcourses.
4. Better integrate with other tools that integrate with Canvas already, such as gradescope. 

The plan for this Fall 2019 is to *not* do any of these, it is to just switch authenticators. This will give everyone involved experience with this, and we can then start experimenting with these features in a small scale.

## Aside: Why not LTI?

[Learning Tools Interoperability](https://www.imsglobal.org/activity/learning-tools-interoperability) is a standard across LMS that can be used to integrate with other tools. We initially built and contributed [LTIAuthenticator](https://github.com/jupyterhub/ltiauthenticator) to the JupyterHub community, and use it successfully in other contexts (such as EdX). We also currently run a hub that can be reached from bcourses via LTI ([docs](https://docs.datahub.berkeley.edu/en/latest/instructor/howto/bcourses.html)).

However, we currently can not use LTI for all the hubs, for the following reasons:

1. LTI currently requires you launch from within bcourses, which breaks a lot of current workflows that involve students clicking [nbgitpuller](https://github.com/jupyterhub/nbgitpuller) links from various other places (email, course website, etc). This is a blocker. See [this wonderful blog post](http://www.claudeonthe.net/blog/?p=301) for some more background on why this is the case, and possible solutions in the LTI spec.
2. As far as we can tell, LTI currently doesn't let us do things like (2) and (3) in the list above easily

We strongly care about and support industry standards over specific APIs wherever possible, and will keep an eye on LTI to see if we can switch over from canvas specific setup to just using LTI

# Next steps

- [x] Fix up our [canvas-test hub](https://canvas-test.datahub.berkeley.edu). It's currently broken due to various other experiments that were conducted on it.
- [ ] Figure out what exactly we need from the wonderful stewards of bcourses in terms of ongoing support. I believe this to be super minimal, and mostly around developer keys only.
- [ ] Aquire Canvas Developer keys for all our hubs (we have a lot!). @felder has access to make these keys, so that's ok!

I'd prefer to get all this done before July 23, when I'm having surgery performed on me.

**Comment by yuvipanda** [comment]
https://canvas-test.datahub.berkeley.edu is now fully operational again!

**Comment by davidwagner** [comment]
The opportunity for better integration with Gradescope is intriguing!

Will this let us support folks who are off-campus but have Google accounts?  (e.g., for the external faculty workshop)

**Comment by yuvipanda** [comment]
Done with https://github.com/berkeley-dsep-infra/datahub/issues/1574
