### ISSUE TITLE
pods per node, pod resource requests

### ISSUE THREAD

**Issue by oneilsh** [berkeley-dsep-infra/datahub#797]
Hi folks - 

Curious about the setup for something like data8 - using n1-highmem-8 nodes, how many pods do you put per node? 100 (kubernetes max), with RAM min 512M max 1G per pod?

Thanks!

**Comment by yuvipanda** [comment]
@oneilsh heya! Yes, that's about right - we don't do anything special, just let the scheduler do its thing.

**Comment by yuvipanda** [comment]
Going to close this one for now! Please re-open if you've other questions :)
