### ISSUE TITLE
jupyter nbextension enable --py gmaps  isn't working!

### ISSUE THREAD

**Issue by kp6689** [berkeley-dsep-infra/datahub#800]
my first post over here! The issue surrounds the problem I face everytime I run the extension enable command.
![image](https://user-images.githubusercontent.com/52552377/60691875-62a2cc80-9f05-11e9-840b-bb4cfd79a6e0.png)

^ thats the error file.

Is the issue because of mutliple python path or something else and in addition to it, there is no extension option in 'EDIT' drop down box, pls refer to the image below.

![image](https://user-images.githubusercontent.com/52552377/60691914-9978e280-9f05-11e9-848c-a16f5dfa3c1a.png)

**Comment by ryanlovett** [comment]
Hi @kp6689 , this repo hosts infrastructure for UC Berkeley's jupyterhubs and its associated docker containers. The error message in your screenshot indicates you are not running your notebook on our infrastructure. Is that correct? If so, you might find additional support at https://discourse.jupyter.org or some other [Jupyter support forum](https://jupyter.org/community).
