### ISSUE TITLE
Request python package datascience==0.13.5 for class Data 8 summer 2019

### ISSUE THREAD

**Issue by davidwagner** [berkeley-dsep-infra/datahub#801]
**Which package do you want installed?**

Change requirements to list `datascience==0.13.5` (currently at `datascience==0.11.4`) and add `folium==0.9.1`.

**Which class will use this package?**

Data 8 over the summer session (and subsequent Data 8 classes).  http://data8.org/su19/

**Which semester will this package be used for?**

Summer 2019; and subsequent offerings of Data 8.

**Comment by felder** [comment]
Done.
