### ISSUE TITLE
Stuck kernels, blank notebooks

### ISSUE THREAD

**Issue by ryanlovett** [berkeley-dsep-infra/datahub#802]
From Natalia Mushegian:
> I'm teaching Data 8 this summer, and we're running into an issue that I've seen in previous semesters but never learned how to resolve - several students have closed out of their notebook while their kernel was stuck, then clicked our pull link for the assignment and ended up with a notebook that was either a) missing their completed work or b) partially or completely blank (entire chunks of cells missing). 
> 
> I thought it was just an issue with notebooks not autosaving due to connectivity issues, but at least one person described to me that they thought it was okay to close their notebook because they had successfully saved their work before running into kernel issues. This is happening slightly more frequently than I'm used to seeing, so I was wondering if you had any idea what could be going on or had suggestions for students (other than telling students to submit to okpy frequently so we have backups, and to make sure they're connected to the internet before closing notebooks).
> 
> The most recent example of this is from [snipped], who lost his hw03 notebook entirely:
https://datahub.berkeley.edu/user/[snipped]/notebooks/materials-su19/materials/su19/hw/hw03/hw03.ipynb
> Is it possible to restore any of his work?

**Comment by yuvipanda** [comment]
So if I understand this correctly, the following is happening:

1. You overrun on memory, and your kernel dies
2. At this point, your *notebook process* also dies, and hence is unable to save anything. At this point, your notebook contents are in your local browser only.
3. When you refresh, this causes local notebook state to be lost.

So I think this would happen if the notebook process itself dies as well.

However, this is predicatd on 'kernel stuck' and what exactly that means...

**Comment by nataliamush** [comment]
Unfortunately, I only have students' accounts of what happened to go on, and that's the student verbiage...none of the assignments where this has happened were likely to have students do anything where they overran the memory.

**Comment by anna-nguyen** [comment]
Hi @yuvipanda @ryanlovett ! We're continuing to run into this issue with Data 8. Students are running our "Intro to Python" notebook, so its unlikely that they've overrun memory. 

One of our TAs was able to replicate the error by running: 

`from client.api.notebook import Notebook
ok = Notebook('hw01.ok')
_ = ok.submit()`

and then not finishng the authentication process, causing the cell to run indefinitely. Once the window is closed and reloaded, all subsequent cells are deleted. 

The broken assignment can be found here: https://datahub.berkeley.edu/user/yanayrosen/notebooks/materials-fa19/materials/fa19/hw/hw01/hw01.ipynb#

**Comment by yuvipanda** [comment]
This issue has been stale for a while, so I'm going to close it. Please re-open if it is still a problem. We're working on a more 'real' support process that can help with issues like this in the future.
