### ISSUE TITLE
Azure set up for fall 2019

### ISSUE THREAD

**Issue by yuvipanda** [berkeley-dsep-infra/datahub#803]
For fall 2019, we'll have two classes on Azure: data100 and data102.

For these, we should do the following:

1. Create a new cluster on AKS with latest version of k8s
2. Set up hubploy in this repo for the new hub
3. Port the same image from old repo to here
4. Use the same NFS server we're using right now

In general, this is to merge the current repo from https://github.com/berkeley-dsep-infra/data100-19s to this repo, keeping as many things the same as possible.

**Comment by ryanlovett** [comment]
data100 is up on Azure via group hack with @felder and @yuvipanda.

data102 is on GKE because Azure was being flaky during deploy. Everything went fine on GKE.
