### ISSUE TITLE
Request R package stargazer lm.beta multcomp lfe for class IAS C118 SUMMER 2019

### ISSUE THREAD

**Issue by chrispyles** [berkeley-dsep-infra/datahub#814]
**Which package do you want installed?**

stargazer
lm.beta
multcomp
lfe

**Which class will use this package?**

[IAS C188](https://classes.berkeley.edu/content/2019-summer-ias-c118-001-lec-001)

Include a link to appropriate entry in https://classes.berkeley.edu/ if available. If not, please mention class name & instructor.

**Which semester will this package be used for?**

Summer 2019

This helps us clean up unused packages after a term ends.

**Any additional information we should know about?**

**Comment by yuvipanda** [comment]
Thanks, @chrispyles! Do you want this in r.datahub.berkeley.edu or datahub.berkeley.edu?

**Comment by chrispyles** [comment]
r.datahub.berkeley.edu

Thanks!

**Comment by yuvipanda** [comment]
@chrispyles can you try now?

**Comment by chrispyles** [comment]
Will inform the professor that these are added and let you know.

**Comment by chrispyles** [comment]
All packages are working

**Comment by yuvipanda** [comment]
thanks for checking, @chrispyles
