### ISSUE TITLE
Can't pull in ds-modules/MCB-32 using interact link

### ISSUE THREAD

**Issue by chrispyles** [berkeley-dsep-infra/datahub#820]
The professor teaching the [MCB-32 module](https://github.com/ds-modules/MCB-32) is trying to load the repository into Datahub using an nbgitpuller link (copied below) but gets an error message each time she tries (image below). The professor has tried deleting the directory recursively in the Datahub terminal and clicking the link again but the error is persisting.

http://datahub.berkeley.edu/user-redirect/interact?account=ds-modules&repo=MCB-32&branch=master&path=.

![image](https://user-images.githubusercontent.com/40970945/61087012-3b5a6c80-a3e9-11e9-8e7e-76e00032cf7a.png)

**Comment by yuvipanda** [comment]
Can you tell us the userid of the professor? Thanks

**Comment by chrispyles** [comment]
The user id is rwball

**Comment by felder** [comment]
@chrispyles Looking in rwball's homedir, there was already an MCB-32 directory.  I suspect that's the cause of this failure.  The directory was mostly empty.  I've moved it to MCB-32.old.

Can you have the professor try it again?

**Comment by chrispyles** [comment]
Will do. Thanks!

**Comment by chrispyles** [comment]
That worked. Thanks again!
