### ISSUE TITLE
Datahub "Unknown error" when accessing notebooks

### ISSUE THREAD

**Issue by rohannarain** [berkeley-dsep-infra/datahub#840]
We've recently had an influx of errors when students try to access their notebooks for assignments; they generally look like the attached image. They seem to happen somewhat often to random students, and we've been able to solve the problem by restarting their Datahub server.

**Comment by ryanlovett** [comment]
Altered version of screenshot:
<img width="1173" alt="error" src="https://user-images.githubusercontent.com/10248125/61501116-d1127080-a982-11e9-8464-54283a7bb003.png">

**Comment by ryanlovett** [comment]
@rohannarain Is it possible that those students are invoking `pip` to install or upgrade python libraries?

**Comment by rohannarain** [comment]
Sorry to get back so late--that's probably not the case, mostly because of the amount of times it's happened.

**Comment by yuvipanda** [comment]
This issue has been stale for a while, so I'm going to close it. Please re-open if it is still a problem. We're working on a more 'real' support process that can help with issues like this in the future.
