### ISSUE TITLE
Logins with full Berkeley email insead of username

### ISSUE THREAD

**Issue by rroggenkemper** [berkeley-dsep-infra/datahub#842]
There have been some cases where, when logging into the datahub, the full email (e.g. username@berkeley.edu) is being used as the username for the hub, instead of just the Berkeley username.

**Comment by yuvipanda** [comment]
I see it, am investigating now

**Comment by yuvipanda** [comment]
@rroggenkemper Can users log out and try now? They should go through bcourses auth instead of google, but everyone's usernames should stay the same... I was going to do this later tonight but decided to push it forward.

**Comment by rroggenkemper** [comment]
I'll confirm with a few other people first, but looks like it's fixed, thanks a lot!
