### ISSUE TITLE
Using datahub from bCourses.

### ISSUE THREAD

**Issue by martinjameswhite** [berkeley-dsep-infra/datahub#879]
I am teaching Physics 209 (electromagnetism) this Fall and would like to use some Python(3) notebooks I have developed.  While many of my students will likely have Python setups of their own, I am intrigued by the datahub framework and would like to try out the bCourses integration.  The instructions suggested I request a "Consumer Key" and "Consumer Secret" by opening an issue, hence this "issue".

(The notebooks run fine on a "standard" datahub instance with no additional packages installed and require minimal memory, compute, etc.  I've tried them by logging into datahub.berkeley.edu directly myself.)

**Comment by yuvipanda** [comment]
Heya! thanks for opening the issue here!

As of last week, datahub.berkeley.edu uses bcourses for login. So you can create a standard 'nbgitpuller' link (via http://nbgitpuller.link), and just put that in your course description. Shouldn't need all the instructions specific to bcourses and LTI.

**Comment by martinjameswhite** [comment]
Ok, that's great to hear.  Thanks!
