### ISSUE TITLE
Request R package here, rlist, checkr for class PHW250FG

### ISSUE THREAD

**Issue by anna-nguyen** [berkeley-dsep-infra/datahub#922]
**Which package do you want installed?**
here, rlist, checkr

**Which class will use this package?**
Public Health W250F+G
https://classes.berkeley.edu/content/2019-fall-pbhlth-w250-001-wbl-001

**Which semester will this package be used for?**
Fall 2019 and subsequent offerings

**Any additional information we should know about?**
This is a follow up from Issue 881 (https://github.com/berkeley-dsep-infra/datahub/issues/881.) We continued tor run into errors when loading the packages above.

**Comment by felder** [comment]
@anna-nguyen can you please be more specific as the errors you're encountering?

When looking at the github repo for checkr, here:
https://github.com/poissonconsulting/checkr

The examples listed in the readme for checkr seem to run correctly.

I've attached an image of what I see.

![Screen Shot 2019-08-12 at 2 55 04 PM](https://user-images.githubusercontent.com/1211730/62901380-7534d080-bd11-11e9-942e-961f7a2022aa.png)

**Comment by felder** [comment]
@anna-nguyen 

Attached is me doing something similar for rlist.  Again, from the package's github README:
https://github.com/renkun-ken/rlist

![Screen Shot 2019-08-12 at 3 03 42 PM](https://user-images.githubusercontent.com/1211730/62901819-8b8f5c00-bd12-11e9-9a14-bd3296275a21.png)

**Comment by anna-nguyen** [comment]
We're not able to run library(...) for any of these packages - I've attached a screenshot of the errors:

![image](https://user-images.githubusercontent.com/31677675/62902136-8252bf00-bd13-11e9-90b4-03e91a57f61a.png)

**Comment by felder** [comment]
@anna-nguyen is this on r.datahub?

**Comment by anna-nguyen** [comment]
@felder It's on datahub.berkeley.edu/user/.../rstudio/ which is where the interact link takes students

**Comment by felder** [comment]
@anna-nguyen Issue #881 specified r.datahub for where the packages were to be installed.

Was that a mistake?

**Comment by anna-nguyen** [comment]
@felder Ah sorry, I didn't catch that. Can we have the packages installed for datahub.berkeley.edu? We've been working there vs r.datahub because our instructional team doesn't currently have admin access for r.datahub (Issue [#882](https://github.com/berkeley-dsep-infra/datahub/issues/882))

**Comment by felder** [comment]
@anna-nguyen Do you need all of the packages referenced in #881 installed or just the 3 mentioned here?

**Comment by anna-nguyen** [comment]
@felder I _think_ that all of the other packages were already installed, and it was just those three that we needed to be added.

**Comment by felder** [comment]
PR #928 merged these changes to production.
