### ISSUE TITLE
Request python package pyreadstat for class SW 282

### ISSUE THREAD

**Issue by chrispyles** [berkeley-dsep-infra/datahub#929]
**Which package do you want installed?**

pyreadstat

**Which class will use this package?**

[SW 282](https://classes.berkeley.edu/content/2019-fall-socwel-282a-001-sem-001)

Include a link to appropriate entry in https://classes.berkeley.edu/ if available. If not, please mention class name & instructor.

**Which semester will this package be used for?**

Fall 2019

This helps us clean up unused packages after a term ends.

**Any additional information we should know about?**

**Comment by felder** [comment]
Done.

**Comment by yuvipanda** [comment]
@chrispyles do you know if this is still being used? I've archived https://github.com/yuvipanda/gradable-nbexport and would like to get rid of it.

**Comment by chrispyles** [comment]
Hmm, I'm not sure. @ericvd-ucb do you know if the SW 282 module is still in use?

**Comment by yuvipanda** [comment]
I only wanted to ask about gradable-nbexport, and that was answered in #930. All good now :)

**Comment by ericvd-ucb** [comment]
Not currently in use
