### ISSUE TITLE
Fix Download as PDF options

### ISSUE THREAD

**Issue by ericvd-ucb** [berkeley-dsep-infra/datahub#965]
My understanding is that there are currently 3 download to pdf options. 

A recent option which is probably superior is currently called "PDF via Chrome" and is all the way at the bottom. I think it would help students to clear up this list and have PDF via chrome relabeled and closer to the top.

**Comment by yuvipanda** [comment]
Tracked in https://github.com/berkeley-dsep-infra/datahub/issues/1461 instead
